// ไฟล์: sentences.js
// รวมประโยคสำหรับเกมเรียงประโยค (Sentence Scramble)

const sentenceDB = [
   // --- เพิ่มเติม: ระดับง่าย (More Easy Sentences) ---
    { en: "I like pizza", th: "ฉันชอบพิซซ่า", level: "easy" },
    { en: "The sun is hot", th: "พระอาทิตย์ร้อน", level: "easy" },
    { en: "My mom cooks food", th: "แม่ของฉันทำอาหาร", level: "easy" },
    { en: "They play games", th: "พวกเขาเล่นเกม", level: "easy" },
    { en: "The cat sleeps", th: "แมวกำลังนอนหลับ", level: "easy" },
    { en: "I have a pen", th: "ฉันมีปากกา", level: "easy" },
    { en: "The sky is blue", th: "ท้องฟ้าเป็นสีฟ้า", level: "easy" },
    { en: "We walk to the park", th: "พวกเราเดินไปสวนสาธารณะ", level: "easy" },
    { en: "He has a red car", th: "เขามีรถสีแดง", level: "easy" },
    { en: "She sings a song", th: "เธอร้องเพลง", level: "easy" },
    { en: "I wash my hands", th: "ฉันล้างมือของฉัน", level: "easy" },
    { en: "The flower is red", th: "ดอกไม้มีสีแดง", level: "easy" },
    { en: "Dad drives a car", th: "พ่อขับรถ", level: "easy" },
    { en: "Fish swim in water", th: "ปลาว่ายในน้ำ", level: "easy" },
    { en: "I see a bird", th: "ฉันเห็นนก", level: "easy" },
    { en: "The boy runs home", th: "เด็กชายวิ่งกลับบ้าน", level: "easy" },
    { en: "She drinks milk", th: "เธอดื่มนม", level: "easy" },
    { en: "We eat rice", th: "พวกเรากินข้าว", level: "easy" },
    { en: "It is a rainy day", th: "มันเป็นวันที่ฝนตก", level: "easy" },
    { en: "My dog is black", th: "หมาของฉันสีดำ", level: "easy" },
    { en: "I open the door", th: "ฉันเปิดประตู", level: "easy" },
    { en: "He closes the window", th: "เขาปิดหน้าต่าง", level: "easy" },
    { en: "The baby cries", th: "ทารกร้องไห้", level: "easy" },
    { en: "I write a letter", th: "ฉันเขียนจดหมาย", level: "easy" },
    { en: "We sit on chairs", th: "พวกเรานั่งบนเก้าอี้", level: "easy" },
    { en: "She buys a hat", th: "เธอซื้อหมวก", level: "easy" },
    { en: "The tree is tall", th: "ต้นไม้สูง", level: "easy" },
    { en: "I listen to music", th: "ฉันฟังเพลง", level: "easy" },
    { en: "They run in the park", th: "พวกเขาวิ่งในสวน", level: "easy" },
    { en: "The moon is white", th: "พระจันทร์สีขาว", level: "easy" },
    { en: "I read a comic", th: "ฉันอ่านหนังสือการ์ตูน", level: "easy" },
    { en: "She loves cats", th: "เธอรักแมว", level: "easy" },
    { en: "He wants a toy", th: "เขาอยากได้ของเล่น", level: "easy" },
    { en: "We are friends", th: "พวกเราเป็นเพื่อนกัน", level: "easy" },
    { en: "The car is slow", th: "รถคันนั้นช้า", level: "easy" },
    { en: "I jump high", th: "ฉันกระโดดสูง", level: "easy" },
    { en: "You look nice", th: "คุณดูดีจัง", level: "easy" },
    { en: "The room is clean", th: "ห้องสะอาด", level: "easy" },
    { en: "I wear a shirt", th: "ฉันสวมเสื้อเชิ้ต", level: "easy" },
    { en: "She has long hair", th: "เธอมีผมยาว", level: "easy" },
    { en: "He eats a banana", th: "เขากินกล้วย", level: "easy" },
    { en: "The water is cold", th: "น้ำเย็น", level: "easy" },
    { en: "I use a computer", th: "ฉันใช้คอมพิวเตอร์", level: "easy" },
    { en: "We watch TV", th: "พวกเราดูทีวี", level: "easy" },
    { en: "It is a sunny day", th: "มันเป็นวันที่แดดออก", level: "easy" },
    { en: "My dad is tall", th: "พ่อของฉันตัวสูง", level: "easy" },
    { en: "I draw a picture", th: "ฉันวาดรูป", level: "easy" },
    { en: "The bus is big", th: "รถบัสคันใหญ่", level: "easy" },
    { en: "She walks to school", th: "เธอเดินไปโรงเรียน", level: "easy" },
    { en: "I am a student", th: "ฉันเป็นนักเรียน", level: "easy" },
    
    // --- เพิ่มเติมชุดที่ 2: ระดับง่าย (More Easy Sentences Set 2) ---
    { en: "I see a lion", th: "ฉันเห็นสิงโต", level: "easy" },
    { en: "The grass is green", th: "หญ้ามีสีเขียว", level: "easy" },
    { en: "We play soccer", th: "พวกเราเล่นฟุตบอล", level: "easy" },
    { en: "She has a doll", th: "เธอมีตุ๊กตา", level: "easy" },
    { en: "The car is blue", th: "รถยนต์มีสีฟ้า", level: "easy" },
    { en: "He drinks tea", th: "เขาดื่มชา", level: "easy" },
    { en: "I love my mom", th: "ฉันรักแม่ของฉัน", level: "easy" },
    { en: "The bird sings", th: "นกร้องเพลง", level: "easy" },
    { en: "It is a hot day", th: "มันเป็นวันที่อากาศร้อน", level: "easy" },
    { en: "They go to the shop", th: "พวกเขาไปที่ร้านค้า", level: "easy" },
    { en: "I have a bike", th: "ฉันมีจักรยาน", level: "easy" },
    { en: "The fish is orange", th: "ปลาตัวนั้นสีส้ม", level: "easy" },
    { en: "She wears a dress", th: "เธอสวมชุดเดรส", level: "easy" },
    { en: "He kicks the ball", th: "เขาเตะลูกบอล", level: "easy" },
    { en: "We eat ice cream", th: "พวกเรากินไอศกรีม", level: "easy" },
    { en: "The star is bright", th: "ดวงดาวส่องแสงสว่าง", level: "easy" },
    { en: "I draw a cat", th: "ฉันวาดรูปแมว", level: "easy" },
    { en: "Mom reads a book", th: "แม่อ่านหนังสือ", level: "easy" },
    { en: "The box is empty", th: "กล่องมันว่างเปล่า", level: "easy" },
    { en: "It is a small dog", th: "มันคือสุนัขตัวเล็ก", level: "easy" },
    { en: "You are my friend", th: "คุณคือเพื่อนของฉัน", level: "easy" },
    { en: "I like bananas", th: "ฉันชอบกล้วย", level: "easy" },
    { en: "She cleans the room", th: "เธอทำความสะอาดห้อง", level: "easy" },
    { en: "He sleeps in bed", th: "เขานอนบนเตียง", level: "easy" },
    { en: "The rain falls", th: "ฝนตกลงมา", level: "easy" },
    { en: "I wash my face", th: "ฉันล้างหน้าของฉัน", level: "easy" },
    { en: "We love pizza", th: "พวกเรารักพิซซ่า", level: "easy" },
    { en: "The ant is small", th: "มดตัวเล็ก", level: "easy" },
    { en: "I brush my hair", th: "ฉันหวีผมของฉัน", level: "easy" },
    { en: "He runs to school", th: "เขาวิ่งไปโรงเรียน", level: "easy" },
    { en: "The snow is white", th: "หิมะมีสีขาว", level: "easy" },
    { en: "She cooks dinner", th: "เธอทำอาหารเย็น", level: "easy" },
    { en: "I play with toys", th: "ฉันเล่นของเล่น", level: "easy" },
    { en: "The pig is pink", th: "หมูมีสีชมพู", level: "easy" },
    { en: "We swim in the pool", th: "พวกเราว่ายน้ำในสระ", level: "easy" },
    { en: "He has a big bag", th: "เขามีกระเป๋าใบใหญ่", level: "easy" },
    { en: "The clock is round", th: "นาฬิกาทรงกลม", level: "easy" },
    { en: "I see the moon", th: "ฉันเห็นพระจันทร์", level: "easy" },
    { en: "She likes red roses", th: "เธอชอบกุหลาบแดง", level: "easy" },
    { en: "They dance well", th: "พวกเขาเต้นเก่ง", level: "easy" },
    { en: "The fire is hot", th: "ไฟร้อน", level: "easy" },
    { en: "I eat an egg", th: "ฉันกินไข่", level: "easy" },
    { en: "He rides a bike", th: "เขาขี่จักรยาน", level: "easy" },
    { en: "The soup is good", th: "ซุปอร่อย", level: "easy" },
    { en: "We are happy", th: "พวกเรามีความสุข", level: "easy" },
    { en: "It is a green tree", th: "มันคือต้นไม้สีเขียว", level: "easy" },
    { en: "I have two hands", th: "ฉันมีสองมือ", level: "easy" },
    { en: "She feeds the dog", th: "เธอให้อาหารสุนัข", level: "easy" },
    { en: "The king is old", th: "พระราชานั้นแก่ชรา", level: "easy" },
    { en: "I smile at you", th: "ฉันยิ้มให้คุณ", level: "easy" },
    
    // --- เพิ่มเติมชุดที่ 3: ระดับง่าย (More Easy Sentences Set 3 - 100 Sentences) ---
    { en: "I eat bread", th: "ฉันกินขนมปัง", level: "easy" },
    { en: "The cow eats grass", th: "วัวกินหญ้า", level: "easy" },
    { en: "He has a black pen", th: "เขามีปากกาสีดำ", level: "easy" },
    { en: "She walks in the garden", th: "เธอเดินในสวน", level: "easy" },
    { en: "We see a rainbow", th: "พวกเราเห็นรุ้งกินน้ำ", level: "easy" },
    { en: "The bird can fly", th: "นกสามารถบินได้", level: "easy" },
    { en: "I like chocolate", th: "ฉันชอบช็อกโกแลต", level: "easy" },
    { en: "He wears a hat", th: "เขาสวมหมวก", level: "easy" },
    { en: "The sea is deep", th: "ทะเลลึก", level: "easy" },
    { en: "Mom makes a cake", th: "แม่ทำเค้ก", level: "easy" },
    { en: "I have a new phone", th: "ฉันมีโทรศัพท์ใหม่", level: "easy" },
    { en: "The dog barks loud", th: "สุนัขเห่าเสียงดัง", level: "easy" },
    { en: "She draws a flower", th: "เธอวาดรูปดอกไม้", level: "easy" },
    { en: "We go to the zoo", th: "พวกเราไปสวนสัตว์", level: "easy" },
    { en: "The coffee is hot", th: "กาแฟร้อน", level: "easy" },
    { en: "I sleep on the sofa", th: "ฉันนอนบนโซฟา", level: "easy" },
    { en: "He plays the guitar", th: "เขาเล่นกีตาร์", level: "easy" },
    { en: "The ant works hard", th: "มดทำงานหนัก", level: "easy" },
    { en: "It is a cold night", th: "มันเป็นคืนที่หนาวเย็น", level: "easy" },
    { en: "They run very fast", th: "พวกเขาวิ่งเร็วมาก", level: "easy" },
    { en: "I drink orange juice", th: "ฉันดื่มน้ำส้ม", level: "easy" },
    { en: "She has blue eyes", th: "เธอมีดวงตาสีฟ้า", level: "easy" },
    { en: "The cat jumps down", th: "แมวกระโดดลงมา", level: "easy" },
    { en: "We read a map", th: "พวกเราอ่านแผนที่", level: "easy" },
    { en: "The bus stops here", th: "รถบัสจอดที่นี่", level: "easy" },
    { en: "I hold a cup", th: "ฉันถือถ้วย", level: "easy" },
    { en: "He kicks the door", th: "เขาเตะประตู", level: "easy" },
    { en: "The leaf is green", th: "ใบไม้มีสีเขียว", level: "easy" },
    { en: "Mom loves me", th: "แม่รักฉัน", level: "easy" },
    { en: "I find a key", th: "ฉันเจอกุญแจ", level: "easy" },
    { en: "The sun sets now", th: "พระอาทิตย์กำลังตกตอนนี้", level: "easy" },
    { en: "She opens the box", th: "เธอเปิดกล่อง", level: "easy" },
    { en: "We sit on the grass", th: "พวกเรานั่งบนพื้นหญ้า", level: "easy" },
    { en: "The king has a crown", th: "พระราชามีมงกุฎ", level: "easy" },
    { en: "I clean my shoes", th: "ฉันทำความสะอาดรองเท้า", level: "easy" },
    { en: "He rides a horse", th: "เขาขี่ม้า", level: "easy" },
    { en: "The room is dark", th: "ห้องมืด", level: "easy" },
    { en: "I hear a sound", th: "ฉันได้ยินเสียง", level: "easy" },
    { en: "She plays with sand", th: "เธอเล่นกับทราย", level: "easy" },
    { en: "The wind blows hard", th: "ลมพัดแรง", level: "easy" },
    { en: "We look at the stars", th: "พวกเรามองดูดาว", level: "easy" },
    { en: "It is a red apple", th: "มันคือแอปเปิ้ลสีแดง", level: "easy" },
    { en: "I buy some milk", th: "ฉันซื้อนม", level: "easy" },
    { en: "He fixes the car", th: "เขาซ่อมรถ", level: "easy" },
    { en: "The duck swims well", th: "เป็ดว่ายน้ำเก่ง", level: "easy" },
    { en: "She cuts the paper", th: "เธอตัดกระดาษ", level: "easy" },
    { en: "I love sweet candy", th: "ฉันรักลูกอมหวานๆ", level: "easy" },
    { en: "The boy is sad", th: "เด็กชายเศร้า", level: "easy" },
    { en: "We walk in the rain", th: "พวกเราเดินตากฝน", level: "easy" },
    { en: "The pig eats food", th: "หมูกินอาหาร", level: "easy" },
    { en: "I smell a rose", th: "ฉันดมดอกกุหลาบ", level: "easy" },
    { en: "He throws a ball", th: "เขาขว้างลูกบอล", level: "easy" },
    { en: "The ice is cold", th: "น้ำแข็งเย็น", level: "easy" },
    { en: "She wears a ring", th: "เธอสวมแหวน", level: "easy" },
    { en: "I miss my dad", th: "ฉันคิดถึงพ่อ", level: "easy" },
    { en: "The train is long", th: "รถไฟขบวนยาว", level: "easy" },
    { en: "We fly a kite", th: "พวกเราเล่นว่าว", level: "easy" },
    { en: "It is a good day", th: "มันเป็นวันที่ดี", level: "easy" },
    { en: "I have a soft bed", th: "ฉันมีเตียงนุ่มๆ", level: "easy" },
    { en: "He drives a truck", th: "เขาขับรถบรรทุก", level: "easy" },
    { en: "The hen lays eggs", th: "แม่ไก่วางไข่", level: "easy" },
    { en: "She combs her hair", th: "เธอหวีผมของเธอ", level: "easy" },
    { en: "I help my mom", th: "ฉันช่วยแม่ของฉัน", level: "easy" },
    { en: "The bat flies at night", th: "ค้างคาวบินตอนกลางคืน", level: "easy" },
    { en: "We clap our hands", th: "พวกเราปรบมือ", level: "easy" },
    { en: "The bear is big", th: "หมีตัวใหญ่", level: "easy" },
    { en: "I give you a gift", th: "ฉันให้ของขวัญคุณ", level: "easy" },
    { en: "He runs a race", th: "เขาวิ่งแข่ง", level: "easy" },
    { en: "The floor is wet", th: "พื้นเปียก", level: "easy" },
    { en: "She picks a flower", th: "เธอเด็ดดอกไม้", level: "easy" },
    { en: "I tie my shoes", th: "ฉันผูกเชือกรองเท้า", level: "easy" },
    { en: "The cake is sweet", th: "เค้กหวาน", level: "easy" },
    { en: "We play hide and seek", th: "พวกเราเล่นซ่อนแอบ", level: "easy" },
    { en: "It is a fat cat", th: "มันคือแมวอ้วน", level: "easy" },
    { en: "I draw a circle", th: "ฉันวาดวงกลม", level: "easy" },
    { en: "He looks at the map", th: "เขามองดูแผนที่", level: "easy" },
    { en: "The snake is long", th: "งูตัวยาว", level: "easy" },
    { en: "She tells a story", th: "เธอเล่าเรื่องราว", level: "easy" },
    { en: "I carry a bag", th: "ฉันถือกระเป๋า", level: "easy" },
    { en: "The sheep eats grass", th: "แกะกินหญ้า", level: "easy" },
    { en: "We build a house", th: "พวกเราสร้างบ้าน", level: "easy" },
    { en: "The fox is smart", th: "จิ้งจอกฉลาด", level: "easy" },
    { en: "I touch my nose", th: "ฉันแตะจมูกของฉัน", level: "easy" },
    { en: "He climbs a tree", th: "เขาปีนต้นไม้", level: "easy" },
    { en: "The bell rings loud", th: "ระฆังดังเสียงดัง", level: "easy" },
    { en: "She likes to dance", th: "เธอชอบเต้นรำ", level: "easy" },
    { en: "I see a big ship", th: "ฉันเห็นเรือลำใหญ่", level: "easy" },
    { en: "The frog jumps high", th: "กบกระโดดสูง", level: "easy" },
    { en: "We wait for the bus", th: "พวกเรารอรถบัส", level: "easy" },
    { en: "It is a quiet place", th: "มันเป็นสถานที่เงียบสงบ", level: "easy" },
    { en: "I write my name", th: "ฉันเขียนชื่อของฉัน", level: "easy" },
    { en: "He sells fruit", th: "เขาขายผลไม้", level: "easy" },
    { en: "The moon is bright", th: "พระจันทร์สว่างไสว", level: "easy" },
    { en: "She hugs her teddy", th: "เธอกอดตุ๊กตาหมี", level: "easy" },
    { en: "I count to ten", th: "ฉันนับหนึ่งถึงสิบ", level: "easy" },
    { en: "The baby is cute", th: "เด็กทารกน่ารัก", level: "easy" },
    { en: "We share our toys", th: "พวกเราแบ่งของเล่นกัน", level: "easy" },
    { en: "The road is wide", th: "ถนนกว้าง", level: "easy" },
    { en: "I close my eyes", th: "ฉันหลับตา", level: "easy" },
    { en: "He catches a fish", th: "เขาจับปลา", level: "easy" },
    // --- เพิ่มเติมชุดที่ 4: ระดับง่าย (More Easy Sentences Set 4 - 100 Sentences) ---
    { en: "I like big dogs", th: "ฉันชอบสุนัขตัวใหญ่", level: "easy" },
    { en: "The bee is yellow", th: "ผึ้งมีสีเหลือง", level: "easy" },
    { en: "She drinks water", th: "เธอดื่มน้ำ", level: "easy" },
    { en: "We go to the beach", th: "พวกเราไปชายหาด", level: "easy" },
    { en: "He has a gold ring", th: "เขามีแหวนทอง", level: "easy" },
    { en: "The corn is yellow", th: "ข้าวโพดมีสีเหลือง", level: "easy" },
    { en: "I sit on the floor", th: "ฉันนั่งบนพื้น", level: "easy" },
    { en: "It is a wet day", th: "มันเป็นวันที่เปียกแฉะ", level: "easy" },
    { en: "They like to swim", th: "พวกเขาชอบว่ายน้ำ", level: "easy" },
    { en: "The owl has big eyes", th: "นกฮูกมีดวงตาโต", level: "easy" },
    { en: "I wear a blue cap", th: "ฉันสวมหมวกแก๊ปสีฟ้า", level: "easy" },
    { en: "Mom cooks eggs", th: "แม่ทำไข่", level: "easy" },
    { en: "The kite flies high", th: "ว่าวบินสูง", level: "easy" },
    { en: "He hits the ball", th: "เขาตีลูกบอล", level: "easy" },
    { en: "She loves her cat", th: "เธอรักแมวของเธอ", level: "easy" },
    { en: "We walk to the shop", th: "พวกเราเดินไปที่ร้านค้า", level: "easy" },
    { en: "The fan is cool", th: "พัดลมเย็น", level: "easy" },
    { en: "I have a red toy", th: "ฉันมีของเล่นสีแดง", level: "easy" },
    { en: "The sky is gray", th: "ท้องฟ้าเป็นสีเทา", level: "easy" },
    { en: "He reads a map", th: "เขาอ่านแผนที่", level: "easy" },
    { en: "She sings very well", th: "เธอร้องเพลงไพเราะมาก", level: "easy" },
    { en: "I eat a green apple", th: "ฉันกินแอปเปิ้ลสีเขียว", level: "easy" },
    { en: "The baby sleeps now", th: "ทารกกำลังหลับตอนนี้", level: "easy" },
    { en: "We see a big plane", th: "พวกเราเห็นเครื่องบินลำใหญ่", level: "easy" },
    { en: "The soup is hot", th: "ซุปร้อน", level: "easy" },
    { en: "I draw a big house", th: "ฉันวาดบ้านหลังใหญ่", level: "easy" },
    { en: "He runs very slow", th: "เขาวิ่งช้ามาก", level: "easy" },
    { en: "The boat is on water", th: "เรืออยู่บนน้ำ", level: "easy" },
    { en: "She buys a new bag", th: "เธอซื้อกระเป๋าใบใหม่", level: "easy" },
    { en: "I have ten fingers", th: "ฉันมีนิ้วสิบนิ้ว", level: "easy" },
    { en: "The cup is full", th: "ถ้วยเต็ม", level: "easy" },
    { en: "We like sweet fruit", th: "พวกเราชอบผลไม้หวาน", level: "easy" },
    { en: "It is a dry season", th: "มันคือฤดูแล้ง", level: "easy" },
    { en: "I touch the wall", th: "ฉันแตะผนัง", level: "easy" },
    { en: "He writes a book", th: "เขาเขียนหนังสือ", level: "easy" },
    { en: "The lamp is bright", th: "โคมไฟสว่าง", level: "easy" },
    { en: "She looks at me", th: "เธอมองมาที่ฉัน", level: "easy" },
    { en: "I play in the mud", th: "ฉันเล่นในโคลน", level: "easy" },
    { en: "The wolf howls", th: "หมาป่าหอน", level: "easy" },
    { en: "We eat breakfast", th: "พวกเรากินอาหารเช้า", level: "easy" },
    { en: "He uses a fork", th: "เขาใช้ส้อม", level: "easy" },
    { en: "The tiger is big", th: "เสือตัวใหญ่", level: "easy" },
    { en: "I see a white cloud", th: "ฉันเห็นเมฆสีขาว", level: "easy" },
    { en: "She wears glasses", th: "เธอสวมแว่นตา", level: "easy" },
    { en: "The bus is yellow", th: "รถบัสสีเหลือง", level: "easy" },
    { en: "I have a brown dog", th: "ฉันมีสุนัขสีน้ำตาล", level: "easy" },
    { en: "He paints a picture", th: "เขาระบายสีรูปภาพ", level: "easy" },
    { en: "The bell is ringing", th: "ระฆังกำลังดัง", level: "easy" },
    { en: "We drink warm milk", th: "พวกเราดื่มนมอุ่นๆ", level: "easy" },
    { en: "It is a busy day", th: "มันเป็นวันที่ยุ่งวุ่นวาย", level: "easy" },
    { en: "I make a sandwich", th: "ฉันทำแซนด์วิช", level: "easy" },
    { en: "The crab walks side", th: "ปูเดินข้าง", level: "easy" },
    { en: "She holds a baby", th: "เธออุ้มเด็กทารก", level: "easy" },
    { en: "I see a green leaf", th: "ฉันเห็นใบไม้สีเขียว", level: "easy" },
    { en: "He likes to run", th: "เขาชอบวิ่ง", level: "easy" },
    { en: "The mouse is small", th: "หนูตัวเล็ก", level: "easy" },
    { en: "We go to the farm", th: "พวกเราไปฟาร์ม", level: "easy" },
    { en: "The ice melts fast", th: "น้ำแข็งละลายเร็ว", level: "easy" },
    { en: "I pull the rope", th: "ฉันดึงเชือก", level: "easy" },
    { en: "She pushes the cart", th: "เธอเข็นรถเข็น", level: "easy" },
    { en: "The day is long", th: "กลางวันยาวนาน", level: "easy" },
    { en: "I hear a bird", th: "ฉันได้ยินเสียงนก", level: "easy" },
    { en: "He wears a tie", th: "เขาผูกเนคไท", level: "easy" },
    { en: "The jam is sweet", th: "แยมหวาน", level: "easy" },
    { en: "We sit in a circle", th: "พวกเรานั่งเป็นวงกลม", level: "easy" },
    { en: "I like cold water", th: "ฉันชอบน้ำเย็น", level: "easy" },
    { en: "The spider has legs", th: "แมงมุมมีขา", level: "easy" },
    { en: "She calls her mom", th: "เธอโทรหาแม่ของเธอ", level: "easy" },
    { en: "It is a new car", th: "มันคือรถคันใหม่", level: "easy" },
    { en: "I jump on the bed", th: "ฉันกระโดดบนเตียง", level: "easy" },
    { en: "He cuts the cake", th: "เขาตัดเค้ก", level: "easy" },
    { en: "The goat eats grass", th: "แพะกินหญ้า", level: "easy" },
    { en: "We wash the car", th: "พวกเราล้างรถ", level: "easy" },
    { en: "I have a pink pen", th: "ฉันมีปากกาสีชมพู", level: "easy" },
    { en: "The drum is loud", th: "กลองเสียงดัง", level: "easy" },
    { en: "She loves to cook", th: "เธอรักการทำอาหาร", level: "easy" },
    { en: "I see a tall tree", th: "ฉันเห็นต้นไม้สูง", level: "easy" },
    { en: "He finds a coin", th: "เขาเจอเหรียญ", level: "easy" },
    { en: "The whale is huge", th: "วาฬตัวใหญ่มาก", level: "easy" },
    { en: "We write a story", th: "พวกเราเขียนเรื่องราว", level: "easy" },
    { en: "I stand up now", th: "ฉันยืนขึ้นตอนนี้", level: "easy" },
    { en: "The pen is blue", th: "ปากกาสีน้ำเงิน", level: "easy" },
    { en: "She gets up early", th: "เธอตื่นนอนแต่เช้า", level: "easy" },
    { en: "I brush my teeth", th: "ฉันแปรงฟันของฉัน", level: "easy" },
    { en: "He goes to work", th: "เขาไปทำงาน", level: "easy" },
    { en: "The sun is yellow", th: "พระอาทิตย์สีเหลือง", level: "easy" },
    { en: "We run to the hill", th: "พวกเราวิ่งไปที่เนินเขา", level: "easy" },
    { en: "I like to read", th: "ฉันชอบอ่าน", level: "easy" },
    { en: "The key is small", th: "กุญแจดอกเล็ก", level: "easy" },
    { en: "She wears a coat", th: "เธอสวมเสื้อโค้ท", level: "easy" },
    { en: "I drink cold milk", th: "ฉันดื่มนมเย็น", level: "easy" },
    { en: "He is a good boy", th: "เขาเป็นเด็กดี", level: "easy" },
    { en: "The pear is green", th: "ลูกแพร์สีเขียว", level: "easy" },
    { en: "We look for shells", th: "พวกเราหาเปลือกหอย", level: "easy" },
    { en: "I say hello to you", th: "ฉันพูดสวัสดีกับคุณ", level: "easy" },
    { en: "The fire is warm", th: "ไฟอบอุ่น", level: "easy" },
    { en: "She buys some eggs", th: "เธอซื้อไข่มาบ้าง", level: "easy" },
    { en: "I smell the food", th: "ฉันได้กลิ่นอาหาร", level: "easy" },
    { en: "He likes the zoo", th: "เขาชอบสวนสัตว์", level: "easy" },
    { en: "The rug is soft", th: "พรมมันนุ่ม", level: "easy" },

// --- ระดับกลาง (Medium Level - 100 Sentences) ---
    { en: "Where do you live", th: "คุณอาศัยอยู่ที่ไหน", level: "medium" },
    { en: "What time is it now", th: "ตอนนี้กี่โมงแล้ว", level: "medium" },
    { en: "Can I have some water", th: "ขอน้ำหน่อยได้ไหม", level: "medium" },
    { en: "She is cooking dinner", th: "เธอกำลังทำอาหารเย็น", level: "medium" },
    { en: "He goes to school by bus", th: "เขาไปโรงเรียนโดยรถบัส", level: "medium" },
    { en: "Do you like spicy food", th: "คุณชอบอาหารเผ็ดไหม", level: "medium" },
    { en: "I am learning English", th: "ฉันกำลังเรียนภาษาอังกฤษ", level: "medium" },
    { en: "My father works in a bank", th: "พ่อของฉันทำงานในธนาคาร", level: "medium" },
    { en: "Why are you crying", th: "ทำไมคุณถึงร้องไห้", level: "medium" },
    { en: "Please open the window", th: "กรุณาเปิดหน้าต่าง", level: "medium" },
    { en: "I want to be a doctor", th: "ฉันอยากเป็นหมอ", level: "medium" },
    { en: "They are playing football", th: "พวกเขากำลังเล่นฟุตบอล", level: "medium" },
    { en: "How much is this shirt", th: "เสื้อตัวนี้ราคาเท่าไหร่", level: "medium" },
    { en: "We will go to the cinema", th: "พวกเราจะไปโรงหนัง", level: "medium" },
    { en: "She has a beautiful voice", th: "เธอมีเสียงที่ไพเราะ", level: "medium" },
    { en: "Are you ready to go", th: "คุณพร้อมที่จะไปหรือยัง", level: "medium" },
    { en: "I forgot my homework", th: "ฉันลืมการบ้านของฉัน", level: "medium" },
    { en: "He doesn't like coffee", th: "เขาไม่ชอบกาแฟ", level: "medium" },
    { en: "The weather is nice today", th: "วันนี้อากาศดี", level: "medium" },
    { en: "Can you speak Thai", th: "คุณพูดภาษาไทยได้ไหม", level: "medium" },
    { en: "I usually wake up at six", th: "โดยปกติฉันตื่นนอนตอนหกโมง", level: "medium" },
    { en: "She is wearing a red dress", th: "เธอกำลังสวมชุดสีแดง", level: "medium" },
    { en: "Where did you buy this", th: "คุณซื้ออันนี้ที่ไหน", level: "medium" },
    { en: "I am waiting for a friend", th: "ฉันกำลังรอเพื่อน", level: "medium" },
    { en: "Do you have any brothers", th: "คุณมีพี่ชายหรือน้องชายไหม", level: "medium" },
    { en: "He is taller than me", th: "เขาตัวสูงกว่าฉัน", level: "medium" },
    { en: "We should go home now", th: "เราควรกลับบ้านเดี๋ยวนี้", level: "medium" },
    { en: "This movie is very funny", th: "หนังเรื่องนี้ตลกมาก", level: "medium" },
    { en: "I need to buy some milk", th: "ฉันจำเป็นต้องซื้อนม", level: "medium" },
    { en: "Can I use your phone", th: "ฉันขอใช้โทรศัพท์ของคุณได้ไหม", level: "medium" },
    { en: "She dances gracefully", th: "เธอเต้นอย่างสง่างาม", level: "medium" },
    { en: "Why is the sky blue", th: "ทำไมท้องฟ้าถึงเป็นสีฟ้า", level: "medium" },
    { en: "I visited my grandmother", th: "ฉันไปเยี่ยมคุณย่าของฉัน", level: "medium" },
    { en: "He runs every morning", th: "เขาวิ่งทุกเช้า", level: "medium" },
    { en: "Do you know the answer", th: "คุณรู้คำตอบไหม", level: "medium" },
    { en: "The train arrives at nine", th: "รถไฟมาถึงตอนเก้าโมง", level: "medium" },
    { en: "I am tired from working", th: "ฉันเหนื่อยจากการทำงาน", level: "medium" },
    { en: "She gave me a present", th: "เธอให้ของขวัญฉัน", level: "medium" },
    { en: "How old are you", th: "คุณอายุเท่าไหร่", level: "medium" },
    { en: "We ate dinner together", th: "พวกเรากินมื้อเย็นด้วยกัน", level: "medium" },
    { en: "He studies very hard", th: "เขาเรียนหนักมาก", level: "medium" },
    { en: "Is this your book", th: "นี่คือหนังสือของคุณใช่ไหม", level: "medium" },
    { en: "I saw a movie yesterday", th: "ฉันดูหนังเมื่อวานนี้", level: "medium" },
    { en: "Please close the door", th: "กรุณาปิดประตู", level: "medium" },
    { en: "She likes reading novels", th: "เธอชอบอ่านนิยาย", level: "medium" },
    { en: "We are going on holiday", th: "พวกเรากำลังจะไปเที่ยววันหยุด", level: "medium" },
    { en: "Can you help me lift this", th: "คุณช่วยฉันยกอันนี้ได้ไหม", level: "medium" },
    { en: "The food tastes good", th: "อาหารรสชาติดี", level: "medium" },
    { en: "I lost my keys today", th: "ฉันทำกุญแจหายวันนี้", level: "medium" },
    { en: "He drives a black car", th: "เขาขับรถสีดำ", level: "medium" },
    { en: "What is your favorite color", th: "สีโปรดของคุณคืออะไร", level: "medium" },
    { en: "They live in a big house", th: "พวกเขาอาศัยในบ้านหลังใหญ่", level: "medium" },
    { en: "I will call you later", th: "ฉันจะโทรหาคุณทีหลัง", level: "medium" },
    { en: "She paints with watercolors", th: "เธอระบายสีด้วยสีน้ำ", level: "medium" },
    { en: "Do you want some tea", th: "คุณต้องการชาไหม", level: "medium" },
    { en: "The shop is closed now", th: "ร้านค้าปิดแล้วตอนนี้", level: "medium" },
    { en: "I am writing an email", th: "ฉันกำลังเขียนอีเมล", level: "medium" },
    { en: "He plays guitar very well", th: "เขาเล่นกีตาร์เก่งมาก", level: "medium" },
    { en: "We walked in the park", th: "พวกเราเดินเล่นในสวน", level: "medium" },
    { en: "Where is the bathroom", th: "ห้องน้ำอยู่ที่ไหน", level: "medium" },
    { en: "This bag is heavy", th: "กระเป๋าใบนี้หนัก", level: "medium" },
    { en: "Can you drive a car", th: "คุณขับรถเป็นไหม", level: "medium" },
    { en: "I enjoy listening to music", th: "ฉันเพลิดเพลินกับการฟังเพลง", level: "medium" },
    { en: "She bought a new dress", th: "เธอซื้อชุดเดรสใหม่", level: "medium" },
    { en: "Why did you do that", th: "ทำไมคุณทำแบบนั้น", level: "medium" },
    { en: "He is fixing his bike", th: "เขากำลังซ่อมจักรยานของเขา", level: "medium" },
    { en: "The baby is sleeping soundly", th: "ทารกกำลังหลับปุ๋ย", level: "medium" },
    { en: "Do you like to travel", th: "คุณชอบท่องเที่ยวไหม", level: "medium" },
    { en: "I have a meeting today", th: "ฉันมีการประชุมวันนี้", level: "medium" },
    { en: "She speaks three languages", th: "เธอพูดได้สามภาษา", level: "medium" },
    { en: "We cleaned the whole house", th: "พวกเราทำความสะอาดทั้งบ้าน", level: "medium" },
    { en: "What did you say", th: "คุณพูดว่าอะไรนะ", level: "medium" },
    { en: "I am looking for my glasses", th: "ฉันกำลังหาแว่นตาของฉัน", level: "medium" },
    { en: "He wants to go home", th: "เขาอยากกลับบ้าน", level: "medium" },
    { en: "The sun rises in the east", th: "พระอาทิตย์ขึ้นทางทิศตะวันออก", level: "medium" },
    { en: "Can I borrow your pen", th: "ฉันขอยืมปากกาคุณได้ไหม", level: "medium" },
    { en: "She is a good teacher", th: "เธอเป็นครูที่ดี", level: "medium" },
    { en: "I don't understand this", th: "ฉันไม่เข้าใจสิ่งนี้", level: "medium" },
    { en: "We play tennis on Sundays", th: "พวกเราเล่นเทนนิสทุกวันอาทิตย์", level: "medium" },
    { en: "How was your day", th: "วันนี้เป็นอย่างไรบ้าง", level: "medium" },
    { en: "The cat is under the table", th: "แมวอยู่ใต้โต๊ะ", level: "medium" },
    { en: "I prefer tea to coffee", th: "ฉันชอบชามากกว่ากาแฟ", level: "medium" },
    { en: "He is watching the news", th: "เขากำลังดูข่าว", level: "medium" },
    { en: "Do you have a pet", th: "คุณมีสัตว์เลี้ยงไหม", level: "medium" },
    { en: "She smiles all the time", th: "เธอยิ้มตลอดเวลา", level: "medium" },
    { en: "I am hungry now", th: "ฉันหิวแล้วตอนนี้", level: "medium" },
    { en: "Where is the nearest bank", th: "ธนาคารที่ใกล้ที่สุดอยู่ที่ไหน", level: "medium" },
    { en: "The flowers smell sweet", th: "ดอกไม้มีกลิ่นหอม", level: "medium" },
    { en: "We finished our work", th: "พวกเราทำงานเสร็จแล้ว", level: "medium" },
    { en: "Can you repeat that", th: "ช่วยพูดซ้ำอีกทีได้ไหม", level: "medium" },
    { en: "He loves to read books", th: "เขารักการอ่านหนังสือ", level: "medium" },
    { en: "I feel much better today", th: "วันนี้ฉันรู้สึกดีขึ้นมาก", level: "medium" },
    { en: "She is making a cake", th: "เธอกำลังทำเค้ก", level: "medium" },
    { en: "What are you doing", th: "คุณกำลังทำอะไร", level: "medium" },
    { en: "I missed the bus", th: "ฉันตกรถบัส", level: "medium" },
    { en: "They are good friends", th: "พวกเขาเป็นเพื่อนที่ดี", level: "medium" },
    { en: "It is going to rain", th: "ฝนกำลังจะตก", level: "medium" },
    { en: "Do you need any help", th: "คุณต้องการความช่วยเหลือไหม", level: "medium" },
    { en: "He forgot his wallet", th: "เขาลืมกระเป๋าสตางค์", level: "medium" },
    { en: "I like listening to jazz", th: "ฉันชอบฟังเพลงแจ๊ส", level: "medium" },
    // --- เพิ่มเติมชุดที่ 2: ระดับกลาง (More Medium Sentences Set 2 - 100 Sentences) ---
    { en: "I wake up at seven", th: "ฉันตื่นนอนตอนเจ็ดโมง", level: "medium" },
    { en: "She is watching TV", th: "เธอกำลังดูทีวี", level: "medium" },
    { en: "We like spicy food", th: "พวกเราชอบอาหารรสจัด", level: "medium" },
    { en: "He plays football well", th: "เขาเล่นฟุตบอลเก่ง", level: "medium" },
    { en: "I study English hard", th: "ฉันเรียนภาษาอังกฤษหนักมาก", level: "medium" },
    { en: "They go to the market", th: "พวกเขาไปตลาด", level: "medium" },
    { en: "My mom cooks dinner", th: "แม่ของฉันทำอาหารเย็น", level: "medium" },
    { en: "The dog is barking", th: "สุนัขกำลังเห่า", level: "medium" },
    { en: "I drink coffee daily", th: "ฉันดื่มกาแฟทุกวัน", level: "medium" },
    { en: "She wears a blue hat", th: "เธอสวมหมวกสีฟ้า", level: "medium" },
    { en: "We travel by train", th: "พวกเราเดินทางโดยรถไฟ", level: "medium" },
    { en: "He reads the news", th: "เขาอ่านข่าว", level: "medium" },
    { en: "I love sunny days", th: "ฉันรักวันที่แดดออก", level: "medium" },
    { en: "They live in a flat", th: "พวกเขาอาศัยในแฟลต", level: "medium" },
    { en: "My dad drives a van", th: "พ่อของฉันขับรถตู้", level: "medium" },
    { en: "The cat sleeps a lot", th: "แมวนอนหลับเยอะมาก", level: "medium" },
    { en: "I listen to the radio", th: "ฉันฟังวิทยุ", level: "medium" },
    { en: "She buys fresh fruit", th: "เธอซื้อผลไม้สด", level: "medium" },
    { en: "We walk in the park", th: "พวกเราเดินในสวนสาธารณะ", level: "medium" },
    { en: "He fixes the computer", th: "เขาซ่อมคอมพิวเตอร์", level: "medium" },
    { en: "I write in my diary", th: "ฉันเขียนบันทึกประจำวัน", level: "medium" },
    { en: "They swim in the sea", th: "พวกเขาว่ายน้ำในทะเล", level: "medium" },
    { en: "My sister is tall", th: "พี่สาวของฉันตัวสูง", level: "medium" },
    { en: "The bird flies away", th: "นกบินจากไป", level: "medium" },
    { en: "I clean my bedroom", th: "ฉันทำความสะอาดห้องนอน", level: "medium" },
    { en: "She sings a pop song", th: "เธอร้องเพลงป๊อป", level: "medium" },
    { en: "We eat lunch at noon", th: "พวกเรากินมื้อเที่ยงตอนเที่ยงวัน", level: "medium" },
    { en: "He helps his friends", th: "เขาช่วยเหลือเพื่อนของเขา", level: "medium" },
    { en: "I need a new phone", th: "ฉันต้องการโทรศัพท์ใหม่", level: "medium" },
    { en: "They run very fast", th: "พวกเขาวิ่งเร็วมาก", level: "medium" },
    { en: "My brother is kind", th: "พี่ชายของฉันใจดี", level: "medium" },
    { en: "The rain stops now", th: "ฝนหยุดตกแล้วตอนนี้", level: "medium" },
    { en: "I visit my uncle", th: "ฉันไปเยี่ยมลุงของฉัน", level: "medium" },
    { en: "She draws a picture", th: "เธอวาดรูปภาพ", level: "medium" },
    { en: "We wait for the bus", th: "พวกเรารอรถบัส", level: "medium" },
    { en: "He tells a funny joke", th: "เขาเล่าเรื่องตลก", level: "medium" },
    { en: "I brush my teeth", th: "ฉันแปรงฟันของฉัน", level: "medium" },
    { en: "They dance all night", th: "พวกเขาเต้นรำทั้งคืน", level: "medium" },
    { en: "My aunt is a nurse", th: "ป้าของฉันเป็นพยาบาล", level: "medium" },
    { en: "The sun is shining", th: "พระอาทิตย์กำลังส่องแสง", level: "medium" },
    { en: "I wash the dishes", th: "ฉันล้างจาน", level: "medium" },
    { en: "She opens the shop", th: "เธอเปิดร้านค้า", level: "medium" },
    { en: "We play video games", th: "พวกเราเล่นวิดีโอเกม", level: "medium" },
    { en: "He wears glasses", th: "เขาสวมแว่นตา", level: "medium" },
    { en: "I pack my suitcase", th: "ฉันจัดกระเป๋าเดินทาง", level: "medium" },
    { en: "They plant flowers", th: "พวกเขาปลูกดอกไม้", level: "medium" },
    { en: "My friend is sick", th: "เพื่อนของฉันป่วย", level: "medium" },
    { en: "The baby cries loud", th: "ทารกร้องไห้เสียงดัง", level: "medium" },
    { en: "I pay with cash", th: "ฉันจ่ายด้วยเงินสด", level: "medium" },
    { en: "She cuts the paper", th: "เธอตัดกระดาษ", level: "medium" },
    { en: "We sit on the bench", th: "พวกเรานั่งบนม้านั่ง", level: "medium" },
    { en: "He kicks the ball", th: "เขาเตะลูกบอล", level: "medium" },
    { en: "I check my email", th: "ฉันเช็คอีเมลของฉัน", level: "medium" },
    { en: "They work in a bank", th: "พวกเขาทำงานในธนาคาร", level: "medium" },
    { en: "My teacher is nice", th: "ครูของฉันนิสัยดี", level: "medium" },
    { en: "The car is broken", th: "รถยนต์เสีย", level: "medium" },
    { en: "I enjoy the movie", th: "ฉันเพลิดเพลินกับหนัง", level: "medium" },
    { en: "She walks to school", th: "เธอเดินไปโรงเรียน", level: "medium" },
    { en: "We meet at the cafe", th: "พวกเราเจอกันที่คาเฟ่", level: "medium" },
    { en: "He learns to drive", th: "เขาเรียนขับรถ", level: "medium" },
    { en: "I forgot the keys", th: "ฉันลืมกุญแจ", level: "medium" },
    { en: "They sell clothes", th: "พวกเขาขายเสื้อผ้า", level: "medium" },
    { en: "My shoes are dirty", th: "รองเท้าของฉันสกปรก", level: "medium" },
    { en: "The clock is fast", th: "นาฬิกาเดินเร็ว", level: "medium" },
    { en: "I want some water", th: "ฉันต้องการน้ำบ้าง", level: "medium" },
    { en: "She paints the wall", th: "เธอทาสีผนัง", level: "medium" },
    { en: "We stay at a hotel", th: "พวกเราพักที่โรงแรม", level: "medium" },
    { en: "He calls his mom", th: "เขาโทรหาแม่ของเขา", level: "medium" },
    { en: "I lose my wallet", th: "ฉันทำกระเป๋าสตางค์หาย", level: "medium" },
    { en: "They build a house", th: "พวกเขาสร้างบ้าน", level: "medium" },
    { en: "My hair is too long", th: "ผมของฉันยาวเกินไป", level: "medium" },
    { en: "The food is cold", th: "อาหารเย็นชืด", level: "medium" },
    { en: "I arrive on time", th: "ฉันมาถึงตรงเวลา", level: "medium" },
    { en: "She uses a laptop", th: "เธอใช้แล็ปท็อป", level: "medium" },
    { en: "We cross the road", th: "พวกเราข้ามถนน", level: "medium" },
    { en: "He rides a bicycle", th: "เขาขี่จักรยาน", level: "medium" },
    { en: "I try new food", th: "ฉันลองอาหารใหม่ๆ", level: "medium" },
    { en: "They look happy", th: "พวกเขาดูมีความสุข", level: "medium" },
    { en: "My bag is heavy", th: "กระเป๋าของฉันหนัก", level: "medium" },
    { en: "The light is red", th: "ไฟเป็นสีแดง", level: "medium" },
    { en: "I ask a question", th: "ฉันถามคำถาม", level: "medium" },
    { en: "She closes the door", th: "เธอปิดประตู", level: "medium" },
    { en: "We share a pizza", th: "พวกเราแบ่งพิซซ่ากัน", level: "medium" },
    { en: "He finds a coin", th: "เขาเจอเหรียญ", level: "medium" },
    { en: "I wear a raincoat", th: "ฉันสวมเสื้อกันฝน", level: "medium" },
    { en: "They watch a game", th: "พวกเขาดูการแข่งขัน", level: "medium" },
    { en: "My room is small", th: "ห้องของฉันเล็ก", level: "medium" },
    { en: "The tea is hot", th: "ชาร้อน", level: "medium" },
    { en: "I save some money", th: "ฉันเก็บเงินบ้าง", level: "medium" },
    { en: "She loves animals", th: "เธอรักสัตว์", level: "medium" },
    { en: "We climb the hill", th: "พวกเราปีนเนินเขา", level: "medium" },
    { en: "He writes a letter", th: "เขาเขียนจดหมาย", level: "medium" },
    { en: "I smell flowers", th: "ฉันดมดอกไม้", level: "medium" },
    { en: "They start early", th: "พวกเขาเริ่มแต่เช้า", level: "medium" },
    { en: "My computer is old", th: "คอมพิวเตอร์ของฉันเก่า", level: "medium" },
    { en: "The bus is late", th: "รถบัสมาสาย", level: "medium" },
    { en: "I take a shower", th: "ฉันอาบน้ำ", level: "medium" },
    { en: "She speaks softly", th: "เธอพูดเสียงเบา", level: "medium" },
    { en: "We leave tomorrow", th: "พวกเราจะไปพรุ่งนี้", level: "medium" },
    { en: "He buys a ticket", th: "เขาซื้อตั๋ว", level: "medium" },
    // --- เพิ่มเติมชุดที่ 3: ระดับกลาง (More Medium Sentences Set 3 - 100 Sentences) ---
    { en: "I wake up early today", th: "วันนี้ฉันตื่นนอนแต่เช้า", level: "medium" },
    { en: "She forgets her bag", th: "เธอลืมกระเป๋าของเธอ", level: "medium" },
    { en: "We watch a funny movie", th: "พวกเราดูหนังตลก", level: "medium" },
    { en: "He knows the answer", th: "เขารู้คำตอบ", level: "medium" },
    { en: "I meet my friends", th: "ฉันเจอเพื่อนของฉัน", level: "medium" },
    { en: "They play in the garden", th: "พวกเขาเล่นในสวน", level: "medium" },
    { en: "My dad repairs the car", th: "พ่อของฉันซ่อมรถ", level: "medium" },
    { en: "The dog chases a cat", th: "สุนัขไล่กวดแมว", level: "medium" },
    { en: "I drink apple juice", th: "ฉันดื่มน้ำแอปเปิ้ล", level: "medium" },
    { en: "She wears a pink dress", th: "เธอสวมชุดเดรสสีชมพู", level: "medium" },
    { en: "We travel to Japan", th: "พวกเราเดินทางไปญี่ปุ่น", level: "medium" },
    { en: "He reads a magazine", th: "เขาอ่านนิตยสาร", level: "medium" },
    { en: "I love rainy days", th: "ฉันรักวันที่ฝนตก", level: "medium" },
    { en: "They live near the park", th: "พวกเขาอาศัยอยู่ใกล้สวนสาธารณะ", level: "medium" },
    { en: "My mom bakes a cake", th: "แม่ของฉันอบเค้ก", level: "medium" },
    { en: "The bird builds a nest", th: "นกสร้างรัง", level: "medium" },
    { en: "I listen to a podcast", th: "ฉันฟังพอดแคสต์", level: "medium" },
    { en: "She buys fresh vegetables", th: "เธอซื้อผักสด", level: "medium" },
    { en: "We walk along the beach", th: "พวกเราเดินเล่นริมชายหาด", level: "medium" },
    { en: "He paints the fence", th: "เขาทาสีรั้ว", level: "medium" },
    { en: "I write a short story", th: "ฉันเขียนเรื่องสั้น", level: "medium" },
    { en: "They swim in the river", th: "พวกเขาว่ายน้ำในแม่น้ำ", level: "medium" },
    { en: "My sister is a student", th: "น้องสาวของฉันเป็นนักเรียน", level: "medium" },
    { en: "The wind blows gently", th: "ลมพัดเบาๆ", level: "medium" },
    { en: "I clean the kitchen", th: "ฉันทำความสะอาดห้องครัว", level: "medium" },
    { en: "She sings in the choir", th: "เธอร้องเพลงในคณะประสานเสียง", level: "medium" },
    { en: "We eat dinner at seven", th: "พวกเรากินมื้อเย็นตอนทุ่มตรง", level: "medium" },
    { en: "He helps his father", th: "เขาช่วยพ่อของเขา", level: "medium" },
    { en: "I need some paper", th: "ฉันต้องการกระดาษบ้าง", level: "medium" },
    { en: "They run a marathon", th: "พวกเขาวิ่งมาราธอน", level: "medium" },
    { en: "My brother plays drums", th: "พี่ชายของฉันตีกลอง", level: "medium" },
    { en: "The rain falls softly", th: "ฝนตกลงมาเบาๆ", level: "medium" },
    { en: "I visit the museum", th: "ฉันไปเยี่ยมชมพิพิธภัณฑ์", level: "medium" },
    { en: "She draws with pencils", th: "เธอวาดรูปด้วยดินสอ", level: "medium" },
    { en: "We wait for the train", th: "พวกเรารอรถไฟ", level: "medium" },
    { en: "He tells a ghost story", th: "เขาเล่าเรื่องผี", level: "medium" },
    { en: "I wash my clothes", th: "ฉันซักเสื้อผ้าของฉัน", level: "medium" },
    { en: "They dance gracefully", th: "พวกเขาเต้นรำอย่างสง่างาม", level: "medium" },
    { en: "My aunt cooks well", th: "ป้าของฉันทำอาหารเก่ง", level: "medium" },
    { en: "The stars shine bright", th: "ดวงดาวส่องแสงสว่าง", level: "medium" },
    { en: "I sweep the floor", th: "ฉันกวาดพื้น", level: "medium" },
    { en: "She opens a window", th: "เธอเปิดหน้าต่างบานหนึ่ง", level: "medium" },
    { en: "We play cards together", th: "พวกเราเล่นไพ่ด้วยกัน", level: "medium" },
    { en: "He wears a uniform", th: "เขาสวมเครื่องแบบ", level: "medium" },
    { en: "I pack my backpack", th: "ฉันจัดกระเป๋าเป้", level: "medium" },
    { en: "They plant a tree", th: "พวกเขาปลูกต้นไม้", level: "medium" },
    { en: "My friend visits me", th: "เพื่อนของฉันมาหาฉัน", level: "medium" },
    { en: "The baby laughs happily", th: "ทารกหัวเราะอย่างมีความสุข", level: "medium" },
    { en: "I pay the bill", th: "ฉันจ่ายบิล", level: "medium" },
    { en: "She cuts her hair", th: "เธอตัดผมของเธอ", level: "medium" },
    { en: "We sit under a tree", th: "พวกเรานั่งใต้ต้นไม้", level: "medium" },
    { en: "He kicks a stone", th: "เขาเตะก้อนหิน", level: "medium" },
    { en: "I check the time", th: "ฉันดูเวลา", level: "medium" },
    { en: "They work in an office", th: "พวกเขาทำงานในออฟฟิศ", level: "medium" },
    { en: "My teacher explains it", th: "ครูของฉันอธิบายสิ่งนั้น", level: "medium" },
    { en: "The car runs fast", th: "รถวิ่งเร็ว", level: "medium" },
    { en: "I enjoy the party", th: "ฉันสนุกกับงานปาร์ตี้", level: "medium" },
    { en: "She walks her dog", th: "เธอพาสุนัขเดินเล่น", level: "medium" },
    { en: "We meet at the park", th: "พวกเราเจอกันที่สวนสาธารณะ", level: "medium" },
    { en: "He learns English", th: "เขาเรียนภาษาอังกฤษ", level: "medium" },
    { en: "I forgot my password", th: "ฉันลืมรหัสผ่าน", level: "medium" },
    { en: "They sell fresh fruit", th: "พวกเขาขายผลไม้สด", level: "medium" },
    { en: "My shoes are new", th: "รองเท้าของฉันใหม่", level: "medium" },
    { en: "The clock strikes twelve", th: "นาฬิกาตีบอกเวลาเที่ยง", level: "medium" },
    { en: "I want to sleep", th: "ฉันอยากนอน", level: "medium" },
    { en: "She paints a portrait", th: "เธอวาดภาพเหมือน", level: "medium" },
    { en: "We stay at home", th: "พวกเราอยู่บ้าน", level: "medium" },
    { en: "He calls a taxi", th: "เขาเรียกแท็กซี่", level: "medium" },
    { en: "I lose my keys", th: "ฉันทำกุญแจหาย", level: "medium" },
    { en: "They build a sandcastle", th: "พวกเขาสร้างปราสาททราย", level: "medium" },
    { en: "My hair is short", th: "ผมของฉันสั้น", level: "medium" },
    { en: "The food is spicy", th: "อาหารมีรสเผ็ด", level: "medium" },
    { en: "I arrive early", th: "ฉันมาถึงก่อนเวลา", level: "medium" },
    { en: "She uses a camera", th: "เธอใช้กล้องถ่ายรูป", level: "medium" },
    { en: "We cross the bridge", th: "พวกเราข้ามสะพาน", level: "medium" },
    { en: "He rides a motorcycle", th: "เขาขี่มอเตอร์ไซค์", level: "medium" },
    { en: "I try to learn", th: "ฉันพยายามที่จะเรียนรู้", level: "medium" },
    { en: "They look tired", th: "พวกเขาดูเหนื่อย", level: "medium" },
    { en: "My bag is light", th: "กระเป๋าของฉันเบา", level: "medium" },
    { en: "The light is green", th: "ไฟเป็นสีเขียว", level: "medium" },
    { en: "I ask for help", th: "ฉันขอความช่วยเหลือ", level: "medium" },
    { en: "She locks the door", th: "เธอล็อคประตู", level: "medium" },
    { en: "We share a secret", th: "พวกเรามีความลับร่วมกัน", level: "medium" },
    { en: "He finds a map", th: "เขาเจอแผนที่", level: "medium" },
    { en: "I wear a jacket", th: "ฉันสวมเสื้อแจ็คเก็ต", level: "medium" },
    { en: "They watch the sunset", th: "พวกเขาดูพระอาทิตย์ตก", level: "medium" },
    { en: "My room is tidy", th: "ห้องของฉันเป็นระเบียบ", level: "medium" },
    { en: "The tea is cold", th: "ชาเย็นชืด", level: "medium" },
    { en: "I save my work", th: "ฉันบันทึกงานของฉัน", level: "medium" },
    { en: "She loves nature", th: "เธอรักธรรมชาติ", level: "medium" },
    { en: "We climb a mountain", th: "พวกเราปีนภูเขา", level: "medium" },
    { en: "He writes a poem", th: "เขาแต่งกลอน", level: "medium" },
    { en: "I smell fresh bread", th: "ฉันได้กลิ่นขนมปังอบใหม่", level: "medium" },
    { en: "They start the game", th: "พวกเขาเริ่มเกม", level: "medium" },
    { en: "My computer is fast", th: "คอมพิวเตอร์ของฉันเร็ว", level: "medium" },
    { en: "The bus is crowded", th: "รถบัสคนแน่น", level: "medium" },
    { en: "I take a photo", th: "ฉันถ่ายรูป", level: "medium" },
    { en: "She speaks clearly", th: "เธอพูดชัดเจน", level: "medium" },
    { en: "We leave today", th: "พวกเราจะไปวันนี้", level: "medium" },
    { en: "He buys a gift", th: "เขาซื้อของขวัญ", level: "medium" },
    // --- ระดับยาก (Hard Level - 100 Sentences) ---
    { en: "I have lived here for ten years", th: "ฉันอาศัยอยู่ที่นี่มาสิบปีแล้ว", level: "hard" },
    { en: "If it rains I will stay at home", th: "ถ้าฝนตก ฉันจะอยู่บ้าน", level: "hard" },
    { en: "She was reading when I called", th: "เธอกำลังอ่านหนังสือตอนที่ฉันโทรหา", level: "hard" },
    { en: "He has not finished his work yet", th: "เขายังทำงานของเขาไม่เสร็จ", level: "hard" },
    { en: "They were playing football yesterday", th: "พวกเขากำลังเล่นฟุตบอลเมื่อวานนี้", level: "hard" },
    { en: "I think that he is a good doctor", th: "ฉันคิดว่าเขาเป็นหมอที่ดี", level: "hard" },
    { en: "The car which I bought is red", th: "รถคันที่ฉันซื้อมามีสีแดง", level: "hard" },
    { en: "Although it was hot we played outside", th: "ถึงแม้อากาศจะร้อน พวกเราก็เล่นข้างนอก", level: "hard" },
    { en: "You should brush your teeth twice a day", th: "คุณควรแปรงฟันวันละสองครั้ง", level: "hard" },
    { en: "I will call you as soon as I arrive", th: "ฉันจะโทรหาคุณทันทีที่ฉันไปถึง", level: "hard" },
    { en: "She has been waiting for two hours", th: "เธอรอมาสองชั่วโมงแล้ว", level: "hard" },
    { en: "If I were you I would go to the doctor", th: "ถ้าฉันเป็นคุณ ฉันจะไปหาหมอ", level: "hard" },
    { en: "He told me that he was tired", th: "เขาบอกฉันว่าเขาเหนื่อย", level: "hard" },
    { en: "The book that you gave me is interesting", th: "หนังสือที่คุณให้ฉันมาน่าสนใจ", level: "hard" },
    { en: "We have never been to Japan before", th: "พวกเราไม่เคยไปญี่ปุ่นมาก่อน", level: "hard" },
    { en: "While I was sleeping the phone rang", th: "ขณะที่ฉันกำลังหลับ โทรศัพท์ก็ดังขึ้น", level: "hard" },
    { en: "You must finish your homework first", th: "คุณต้องทำการบ้านให้เสร็จก่อน", level: "hard" },
    { en: "I do not know where he lives", th: "ฉันไม่รู้ว่าเขาอาศัยอยู่ที่ไหน", level: "hard" },
    { en: "She can speak English and French well", th: "เธอพูดภาษาอังกฤษและฝรั่งเศสได้ดี", level: "hard" },
    { en: "The train had left when we arrived", th: "รถไฟออกไปแล้วตอนที่พวกเรามาถึง", level: "hard" },
    { en: "I would like to order a pizza please", th: "ฉันขอสั่งพิซซ่าหน่อยครับ/ค่ะ", level: "hard" },
    { en: "He is the man who helped me yesterday", th: "เขาคือผู้ชายคนที่ช่วยฉันเมื่อวานนี้", level: "hard" },
    { en: "It is important to eat healthy food", th: "มันสำคัญที่จะกินอาหารเพื่อสุขภาพ", level: "hard" },
    { en: "Do you know how to use this machine", th: "คุณรู้วิธีใช้เครื่องจักรนี้ไหม", level: "hard" },
    { en: "I was wondering if you could help me", th: "ฉันสงสัยว่าคุณพอจะช่วยฉันได้ไหม", level: "hard" },
    { en: "She promised that she would come back", th: "เธอสัญญาว่าเธอจะกลับมา", level: "hard" },
    { en: "We used to live in a small village", th: "พวกเราเคยอาศัยอยู่ในหมู่บ้านเล็กๆ", level: "hard" },
    { en: "If you study hard you will pass the exam", th: "ถ้าคุณเรียนหนัก คุณจะสอบผ่าน", level: "hard" },
    { en: "He asked me what time it was", th: "เขาถามฉันว่ากี่โมงแล้ว", level: "hard" },
    { en: "This is the most beautiful place I know", th: "นี่คือสถานที่ที่สวยที่สุดที่ฉันรู้จัก", level: "hard" },
    { en: "I have just finished my dinner", th: "ฉันเพิ่งกินมื้อเย็นเสร็จ", level: "hard" },
    { en: "She did not go to school because she was sick", th: "เธอไม่ได้ไปโรงเรียนเพราะเธอป่วย", level: "hard" },
    { en: "There are many people in the park today", th: "มีผู้คนมากมายในสวนสาธารณะวันนี้", level: "hard" },
    { en: "I am going to visit my grandmother tomorrow", th: "ฉันจะไปเยี่ยมคุณย่าของฉันพรุ่งนี้", level: "hard" },
    { en: "He could swim when he was five years old", th: "เขาว่ายน้ำได้ตอนที่เขาอายุห้าขวบ", level: "hard" },
    { en: "The letter was written by my friend", th: "จดหมายฉบับนี้ถูกเขียนโดยเพื่อนของฉัน", level: "hard" },
    { en: "We were watching TV when the lights went out", th: "พวกเรากำลังดูทีวีตอนที่ไฟดับ", level: "hard" },
    { en: "I want to know why you are late", th: "ฉันอยากรู้ว่าทำไมคุณถึงมาสาย", level: "hard" },
    { en: "She is looking forward to seeing you", th: "เธอกำลังตั้งตารอที่จะได้พบคุณ", level: "hard" },
    { en: "He prefers coffee rather than tea", th: "เขาชอบกาแฟมากกว่าชา", level: "hard" },
    { en: "It is too dangerous to go out at night", th: "มันอันตรายเกินไปที่จะออกไปข้างนอกตอนกลางคืน", level: "hard" },
    { en: "I have lost the keys that you gave me", th: "ฉันทำกุญแจที่คุณให้ฉันหายไปแล้ว", level: "hard" },
    { en: "If I had money I would buy a car", th: "ถ้าฉันมีเงิน ฉันจะซื้อรถ", level: "hard" },
    { en: "She asked him to open the window", th: "เธอขอให้เขาเปิดหน้าต่าง", level: "hard" },
    { en: "They have been married for twenty years", th: "พวกเขาแต่งงานกันมาเป็นเวลา 20 ปีแล้ว", level: "hard" },
    { en: "I remember playing here as a child", th: "ฉันจำได้ว่าเคยเล่นที่นี่ตอนเป็นเด็ก", level: "hard" },
    { en: "He denied stealing the money from the bag", th: "เขาปฏิเสธว่าไม่ได้ขโมยเงินจากกระเป๋า", level: "hard" },
    { en: "The weather is getting colder every day", th: "อากาศกำลังหนาวขึ้นทุกวัน", level: "hard" },
    { en: "We should have started earlier this morning", th: "พวกเราควรจะเริ่มให้เร็วกว่านี้เมื่อเช้า", level: "hard" },
    { en: "I am not sure if I can come", th: "ฉันไม่แน่ใจว่าฉันจะมาได้ไหม", level: "hard" },
    { en: "She made me a cake for my birthday", th: "เธอทำเค้กให้ฉันสำหรับวันเกิดของฉัน", level: "hard" },
    { en: "He stopped smoking two years ago", th: "เขาเลิกสูบบุหรี่เมื่อสองปีก่อน", level: "hard" },
    { en: "I will wait here until you return", th: "ฉันจะรอที่นี่จนกว่าคุณจะกลับมา", level: "hard" },
    { en: "They were not listening to the teacher", th: "พวกเขาไม่ได้กำลังฟังครู", level: "hard" },
    { en: "My parents want me to study medicine", th: "พ่อแม่ของฉันอยากให้ฉันเรียนแพทย์", level: "hard" },
    { en: "The house was built in the last century", th: "บ้านหลังนี้ถูกสร้างขึ้นในศตวรรษที่แล้ว", level: "hard" },
    { en: "I have seen that movie three times already", th: "ฉันดูหนังเรื่องนั้นมาสามรอบแล้ว", level: "hard" },
    { en: "She is the smartest student in the class", th: "เธอเป็นนักเรียนที่ฉลาดที่สุดในชั้นเรียน", level: "hard" },
    { en: "We are planning to go on a trip", th: "พวกเรากำลังวางแผนที่จะไปเที่ยว", level: "hard" },
    { en: "He does not know what to do next", th: "เขาไม่รู้ว่าจะทำอะไรต่อไป", level: "hard" },
    { en: "It is necessary to arrive on time", th: "มันจำเป็นที่จะต้องมาถึงตรงเวลา", level: "hard" },
    { en: "I wish I could fly like a bird", th: "ฉันปรารถนาว่าฉันจะบินได้เหมือนนก", level: "hard" },
    { en: "She enjoys reading books in her free time", th: "เธอสนุกกับการอ่านหนังสือในเวลาว่าง", level: "hard" },
    { en: "They decided to stay at a hotel", th: "พวกเขาตัดสินใจที่จะพักที่โรงแรม", level: "hard" },
    { en: "He apologized for being late to the meeting", th: "เขาขอโทษที่มาประชุมสาย", level: "hard" },
    { en: "I am interested in learning new languages", th: "ฉันสนใจในการเรียนรู้ภาษาใหม่ๆ", level: "hard" },
    { en: "The problem is too difficult to solve", th: "ปัญหามันยากเกินไปที่จะแก้ไข", level: "hard" },
    { en: "We ran out of gas on the highway", th: "พวกเราน้ำมันหมดบนทางด่วน", level: "hard" },
    { en: "He is used to waking up early", th: "เขาชินกับการตื่นนอนแต่เช้า", level: "hard" },
    { en: "I will let you know when I am ready", th: "ฉันจะบอกให้คุณรู้เมื่อฉันพร้อม", level: "hard" },
    { en: "She suggested going to the cinema together", th: "เธอเสนอให้ไปดูหนังด้วยกัน", level: "hard" },
    { en: "They accused him of breaking the window", th: "พวกเขากล่าวหาว่าเขาทำหน้าต่างแตก", level: "hard" },
    { en: "My car broke down on the way home", th: "รถของฉันเสียระหว่างทางกลับบ้าน", level: "hard" },
    { en: "I can not afford to buy a new house", th: "ฉันไม่มีเงินพอที่จะซื้อบ้านหลังใหม่", level: "hard" },
    { en: "She looks as if she has seen a ghost", th: "เธอดูราวกับว่าเธอเห็นผีมา", level: "hard" },
    { en: "He is good at playing the piano", th: "เขาเก่งในการเล่นเปียโน", level: "hard" },
    { en: "It takes about an hour to get there", th: "ใช้เวลาประมาณหนึ่งชั่วโมงเพื่อไปถึงที่นั่น", level: "hard" },
    { en: "I would rather stay home than go out", th: "ฉันอยากอยู่บ้านมากกว่าออกไปข้างนอก", level: "hard" },
    { en: "She has gone to the supermarket to buy food", th: "เธอไปซูเปอร์มาร์เก็ตเพื่อซื้ออาหาร", level: "hard" },
    { en: "We are looking for a place to eat", th: "พวกเรากำลังหาสถานที่กินข้าว", level: "hard" },
    { en: "He managed to finish the work on time", th: "เขาจัดการทำงานให้เสร็จทันเวลา", level: "hard" },
    { en: "I regret not studying harder for the exam", th: "ฉันเสียใจที่ไม่ได้เรียนให้หนักกว่านี้สำหรับการสอบ", level: "hard" },
    { en: "She reminded me to call my mother", th: "เธอเตือนฉันให้โทรหาแม่", level: "hard" },
    { en: "They offered to help us with the moving", th: "พวกเขาเสนอที่จะช่วยพวกเราย้ายของ", level: "hard" },
    { en: "My phone battery is about to die", th: "แบตเตอรี่โทรศัพท์ของฉันกำลังจะหมด", level: "hard" },
    { en: "The teacher explained the lesson very clearly", th: "ครูอธิบายบทเรียนอย่างชัดเจนมาก", level: "hard" },
    { en: "I have not seen him since last week", th: "ฉันไม่ได้เจอเขาตั้งแต่สัปดาห์ที่แล้ว", level: "hard" },
    { en: "She is capable of doing great things", th: "เธอมีความสามารถที่จะทำสิ่งที่ยิ่งใหญ่ได้", level: "hard" },
    { en: "We must protect the environment for our future", th: "พวกเราต้องปกป้องสิ่งแวดล้อมเพื่ออนาคตของเรา", level: "hard" },
    { en: "He promised not to tell anyone the secret", th: "เขาสัญญาว่าจะไม่บอกความลับกับใคร", level: "hard" },
    { en: "It seems that it is going to rain soon", th: "ดูเหมือนว่าฝนกำลังจะตกในเร็วๆ นี้", level: "hard" },
    { en: "I doubt that he will come to the party", th: "ฉันสงสัยว่าเขาจะมางานปาร์ตี้ไหม", level: "hard" },
    { en: "She depends on her parents for money", th: "เธอพึ่งพาพ่อแม่เรื่องเงิน", level: "hard" },
    { en: "They succeeded in climbing the highest mountain", th: "พวกเขาประสบความสำเร็จในการปีนภูเขาที่สูงที่สุด", level: "hard" },
    { en: "My dream is to travel around the world", th: "ความฝันของฉันคือการเดินทางรอบโลก", level: "hard" },
    { en: "The bridge was destroyed by the strong storm", th: "สะพานถูกทำลายโดยพายุที่รุนแรง", level: "hard" },
    { en: "I strongly believe that you can do it", th: "ฉันเชื่ออย่างแรงกล้าว่าคุณทำได้", level: "hard" },
    { en: "She was surprised to see him at the party", th: "เธอประหลาดใจที่เห็นเขาที่งานปาร์ตี้", level: "hard" },
    { en: "We have to leave early to catch the flight", th: "พวกเราต้องออกแต่เช้าเพื่อไปขึ้นเครื่องบินให้ทัน", level: "hard" },
    { en: "He refused to answer any of my questions", th: "เขาปฏิเสธที่จะตอบคำถามของฉัน", level: "hard" },
    // --- เพิ่มเติมชุดที่ 2: ระดับยาก (More Hard Sentences Set 2 - 100 Sentences) ---
    { en: "Unless you hurry up we will miss the train", th: "เว้นแต่คุณจะรีบ เราจะตกรถไฟ", level: "hard" },
    { en: "I would have helped you if I had known", th: "ฉันคงจะช่วยคุณไปแล้วถ้าฉันรู้", level: "hard" },
    { en: "The report must be finished by tomorrow morning", th: "รายงานจะต้องเสร็จภายในพรุ่งนี้เช้า", level: "hard" },
    { en: "He acted as if nothing had happened", th: "เขาทำตัวราวกับว่าไม่มีอะไรเกิดขึ้น", level: "hard" },
    { en: "She is the woman whose car was stolen", th: "เธอคือผู้หญิงคนที่รถถูกขโมย", level: "hard" },
    { en: "I am not used to driving on the left", th: "ฉันไม่ชินกับการขับรถชิดซ้าย", level: "hard" },
    { en: "Despite the rain we went for a walk", th: "แม้ว่าฝนจะตก พวกเราก็ออกไปเดินเล่น", level: "hard" },
    { en: "He explained how to solve the problem clearly", th: "เขาอธิบายวิธีแก้ปัญหาอย่างชัดเจน", level: "hard" },
    { en: "It is strictly forbidden to smoke in here", th: "ห้ามสูบบุหรี่ในนี้อย่างเด็ดขาด", level: "hard" },
    { en: "I wish I had studied harder for the test", th: "ฉันหวังว่าฉันจะเรียนให้หนักกว่านี้สำหรับการสอบ", level: "hard" },
    { en: "The doctor advised him to stop eating sugar", th: "หมอแนะนำให้เขาเลิกกินน้ำตาล", level: "hard" },
    { en: "She was so tired that she fell asleep immediately", th: "เธอเหนื่อยมากจนผล็อยหลับไปทันที", level: "hard" },
    { en: "We are looking forward to our summer holiday", th: "พวกเรากำลังตั้งตารอวันหยุดฤดูร้อนของเรา", level: "hard" },
    { en: "He has been working on this project for months", th: "เขาทำโปรเจกต์นี้มาหลายเดือนแล้ว", level: "hard" },
    { en: "No sooner had I arrived than the phone rang", th: "ทันทีที่ฉันมาถึง โทรศัพท์ก็ดังขึ้น", level: "hard" },
    { en: "You had better go to see a doctor", th: "คุณควรไปหาหมอดีกว่า", level: "hard" },
    { en: "The meeting was cancelled due to bad weather", th: "การประชุมถูกยกเลิกเนื่องจากสภาพอากาศแย่", level: "hard" },
    { en: "I wonder why she didn't come to the party", th: "ฉันสงสัยว่าทำไมเธอไม่มางานปาร์ตี้", level: "hard" },
    { en: "It is no use crying over spilt milk", th: "ไม่มีประโยชน์ที่จะมาร้องไห้ฟูมฟายกับสิ่งที่เสียไปแล้ว", level: "hard" },
    { en: "She accused him of stealing her diamond ring", th: "เธอกล่าวหาว่าเขาขโมยแหวนเพชรของเธอ", level: "hard" },
    { en: "He insisted on paying for the dinner himself", th: "เขายืนกรานที่จะจ่ายค่าอาหารเย็นเอง", level: "hard" },
    { en: "I would rather drink tea than coffee today", th: "วันนี้ฉันอยากดื่มชามากกว่ากาแฟ", level: "hard" },
    { en: "The thief was caught by the police yesterday", th: "ขโมยถูกตำรวจจับเมื่อวานนี้", level: "hard" },
    { en: "She asked me if I had seen her keys", th: "เธอถามฉันว่าฉันเห็นกุญแจของเธอไหม", level: "hard" },
    { en: "If only I had more time to travel", th: "ถ้าเพียงแต่ฉันมีเวลาเที่ยวมากกว่านี้", level: "hard" },
    { en: "He pretends not to hear what I say", th: "เขาแกล้งทำเป็นไม่ได้ยินสิ่งที่ฉันพูด", level: "hard" },
    { en: "It is impossible to please everyone all the time", th: "มันเป็นไปไม่ได้ที่จะทำให้ทุกคนพอใจตลอดเวลา", level: "hard" },
    { en: "I prefer reading books to watching television", th: "ฉันชอบอ่านหนังสือมากกว่าดูทีวี", level: "hard" },
    { en: "The harder you work the luckier you get", th: "ยิ่งคุณทำงานหนัก คุณก็ยิ่งโชคดี", level: "hard" },
    { en: "She succeeded in passing the driving test finally", th: "ในที่สุดเธอก็สอบใบขับขี่ผ่านจนได้", level: "hard" },
    { en: "We should prevent the pollution of our environment", th: "เราควรป้องกันมลพิษในสิ่งแวดล้อมของเรา", level: "hard" },
    { en: "He is likely to win the competition this year", th: "มีแนวโน้มว่าเขาจะชนะการแข่งขันปีนี้", level: "hard" },
    { en: "I have neither seen him nor heard from him", th: "ฉันไม่เคยเห็นเขาและไม่ได้ข่าวจากเขาเลย", level: "hard" },
    { en: "The old house needs to be renovated completely", th: "บ้านหลังเก่าจำเป็นต้องได้รับการบูรณะใหม่ทั้งหมด", level: "hard" },
    { en: "She decided to quit her job and travel", th: "เธอตัดสินใจลาออกจากงานและไปท่องเที่ยว", level: "hard" },
    { en: "Had I known the truth I would have told you", th: "หากฉันรู้ความจริง ฉันคงบอกคุณไปแล้ว", level: "hard" },
    { en: "He was disappointed with his exam results", th: "เขาผิดหวังกับผลสอบของเขา", level: "hard" },
    { en: "I find it difficult to wake up early", th: "ฉันพบว่ามันยากที่จะตื่นแต่เช้า", level: "hard" },
    { en: "Do you mind if I open the window", th: "คุณจะว่าอะไรไหมถ้าฉันจะเปิดหน้าต่าง", level: "hard" },
    { en: "It is worth visiting the museum in this city", th: "มันคุ้มค่าที่จะไปเยี่ยมชมพิพิธภัณฑ์ในเมืองนี้", level: "hard" },
    { en: "She encouraged me to learn a new language", th: "เธอสนับสนุนให้ฉันเรียนภาษาใหม่", level: "hard" },
    { en: "They arrived at the airport just in time", th: "พวกเขามาถึงสนามบินทันเวลาพอดี", level: "hard" },
    { en: "My parents let me go out with friends", th: "พ่อแม่ของฉันอนุญาตให้ฉันออกไปเที่ยวกับเพื่อน", level: "hard" },
    { en: "The cake smells as if it is burning", th: "เค้กมีกลิ่นเหมือนกำลังไหม้", level: "hard" },
    { en: "I will get used to living here soon", th: "ฉันจะชินกับการอยู่ที่นี่ในไม่ช้า", level: "hard" },
    { en: "He denied having broken the valuable vase", th: "เขาปฏิเสธว่าไม่ได้ทำแจกันล้ำค่าแตก", level: "hard" },
    { en: "She was warned not to touch the wire", th: "เธอถูกเตือนไม่ให้แตะต้องสายไฟ", level: "hard" },
    { en: "Whatever you do do it with all your heart", th: "ไม่ว่าคุณจะทำอะไร จงทำด้วยหัวใจทั้งหมดของคุณ", level: "hard" },
    { en: "I suggest that we should take a taxi", th: "ฉันแนะนำว่าเราควรนั่งแท็กซี่", level: "hard" },
    { en: "The mountain is covered with snow all year", th: "ภูเขาถูกปกคลุมด้วยหิมะตลอดทั้งปี", level: "hard" },
    { en: "He is responsible for managing the sales team", th: "เขารับผิดชอบในการจัดการทีมขาย", level: "hard" },
    { en: "It is obvious that she is very intelligent", th: "มันชัดเจนมากว่าเธอฉลาดมาก", level: "hard" },
    { en: "I regret to inform you that you failed", th: "ฉันเสียใจที่จะแจ้งให้ทราบว่าคุณสอบตก", level: "hard" },
    { en: "She spent all day cleaning her room", th: "เธอใช้เวลาทั้งวันทำความสะอาดห้องของเธอ", level: "hard" },
    { en: "We ran out of time during the exam", th: "พวกเราหมดเวลาระหว่างการสอบ", level: "hard" },
    { en: "He admitted that he had made a mistake", th: "เขายอมรับว่าเขาทำผิดพลาด", level: "hard" },
    { en: "I am thinking of buying a new computer", th: "ฉันกำลังคิดว่าจะซื้อคอมพิวเตอร์ใหม่", level: "hard" },
    { en: "The bridge connects the two sides of the river", th: "สะพานเชื่อมสองฝั่งของแม่น้ำเข้าด้วยกัน", level: "hard" },
    { en: "She appears to be very happy with her job", th: "เธอดูเหมือนจะมีความสุขมากกับงานของเธอ", level: "hard" },
    { en: "I have no idea how to use this software", th: "ฉันไม่รู้เลยว่าจะใช้ซอฟต์แวร์นี้ยังไง", level: "hard" },
    { en: "He is capable of running a marathon easily", th: "เขามีความสามารถที่จะวิ่งมาราธอนได้สบายๆ", level: "hard" },
    { en: "Please remind me to call my boss later", th: "ช่วยเตือนฉันให้โทรหาเจ้านายทีหลังด้วย", level: "hard" },
    { en: "I was about to leave when you arrived", th: "ฉันกำลังจะออกไปตอนที่คุณมาถึง", level: "hard" },
    { en: "She is dedicated to helping poor people", th: "เธออุทิศตนเพื่อช่วยเหลือคนยากจน", level: "hard" },
    { en: "The news surprised everyone in the room", th: "ข่าวนั้นทำให้ทุกคนในห้องประหลาดใจ", level: "hard" },
    { en: "I would rather you stayed at home tonight", th: "ฉันอยากให้คุณอยู่บ้านคืนนี้มากกว่า", level: "hard" },
    { en: "He failed to convince me of his innocence", th: "เขาล้มเหลวในการทำให้ฉันเชื่อในความบริสุทธิ์ของเขา", level: "hard" },
    { en: "It is a waste of time arguing with him", th: "มันเสียเวลาเปล่าที่จะเถียงกับเขา", level: "hard" },
    { en: "She resembles her mother in many ways", th: "เธอเหมือนแม่ของเธอในหลายๆ ด้าน", level: "hard" },
    { en: "We are grateful for your kind support", th: "พวกเราซาบซึ้งสำหรับการสนับสนุนที่ใจดีของคุณ", level: "hard" },
    { en: "He objected to the plan proposed by the manager", th: "เขาคัดค้านแผนที่ผู้จัดการเสนอมา", level: "hard" },
    { en: "I am confident that we will win the game", th: "ฉันมั่นใจว่าเราจะชนะเกมนี้", level: "hard" },
    { en: "The instructions were too difficult to understand", th: "คำแนะนำนั้นยากเกินกว่าจะเข้าใจ", level: "hard" },
    { en: "She specializes in teaching young children", th: "เธอเชี่ยวชาญในการสอนเด็กเล็ก", level: "hard" },
    { en: "He broke his leg while playing football yesterday", th: "เขาขาหักขณะเล่นฟุตบอลเมื่อวานนี้", level: "hard" },
    { en: "I appreciate your help very much indeed", th: "ฉันซาบซึ้งในความช่วยเหลือของคุณมากจริงๆ", level: "hard" },
    { en: "The factory produces thousands of cars daily", th: "โรงงานผลิตรถยนต์หลายพันคันต่อวัน", level: "hard" },
    { en: "She participated in the singing competition last week", th: "เธอเข้าร่วมการแข่งขันร้องเพลงเมื่อสัปดาห์ที่แล้ว", level: "hard" },
    { en: "It is essential to drink enough water daily", th: "เป็นเรื่องจำเป็นที่ต้องดื่มน้ำให้เพียงพอทุกวัน", level: "hard" },
    { en: "He claimed that he had never seen her before", th: "เขาอ้างว่าเขาไม่เคยเห็นเธอมาก่อน", level: "hard" },
    { en: "I am accustomed to waking up early now", th: "ตอนนี้ฉันคุ้นเคยกับการตื่นนอนแต่เช้าแล้ว", level: "hard" },
    { en: "She focused on finishing her university degree", th: "เธอจดจ่อกับการเรียนให้จบปริญญามหาวิทยาลัย", level: "hard" },
    { en: "They estimated the cost of the project", th: "พวกเขาประเมินค่าใช้จ่ายของโครงการ", level: "hard" },
    { en: "My ambition is to become a famous writer", th: "ความทะเยอทะยานของฉันคือการเป็นนักเขียนที่มีชื่อเสียง", level: "hard" },
    { en: "The experiment resulted in a great discovery", th: "การทดลองส่งผลให้เกิดการค้นพบที่ยิ่งใหญ่", level: "hard" },
    { en: "I suspect that he is lying to us", th: "ฉันสงสัยว่าเขากำลังโกหกพวกเรา", level: "hard" },
    { en: "She devoted her life to scientific research", th: "เธออุทิศชีวิตของเธอให้กับการวิจัยทางวิทยาศาสตร์", level: "hard" },
    { en: "We rely on technology for communication today", th: "ทุกวันนี้เราพึ่งพาเทคโนโลยีในการสื่อสาร", level: "hard" },
    { en: "He apologized for his rude behavior yesterday", th: "เขาขอโทษสำหรับพฤติกรรมหยาบคายของเขาเมื่อวานนี้", level: "hard" },
    { en: "It is rare to see such a beautiful bird", th: "มันหาดูได้ยากที่จะเห็นนกที่สวยงามเช่นนี้", level: "hard" },
    { en: "I am convinced that this is the right way", th: "ฉันเชื่อมั่นว่านี่คือทางที่ถูกต้อง", level: "hard" },
    { en: "She intends to study abroad next year", th: "เธอตั้งใจที่จะไปเรียนต่อต่างประเทศปีหน้า", level: "hard" },
    { en: "The building collapsed during the earthquake", th: "ตึกถล่มลงมาในระหว่างเกิดแผ่นดินไหว", level: "hard" },
    { en: "He managed to solve the puzzle in minutes", th: "เขาจัดการแก้ปริศนาได้ภายในไม่กี่นาที", level: "hard" },
    { en: "I urge you to consider this opportunity carefully", th: "ฉันกระตุ้นให้คุณพิจารณาโอกาสนี้อย่างระมัดระวัง", level: "hard" },
    { en: "She is keen on learning about history", th: "เธอกระตือรือร้นที่จะเรียนรู้เกี่ยวกับประวัติศาสตร์", level: "hard" },
    { en: "They established a new company last month", th: "พวกเขาก่อตั้งบริษัทใหม่เมื่อเดือนที่แล้ว", level: "hard" },
    { en: "My goal is to master three languages fluently", th: "เป้าหมายของฉันคือการเก่งสามภาษาอย่างคล่องแคล่ว", level: "hard" },
    { en: "The evidence proves that he is innocent", th: "หลักฐานพิสูจน์ว่าเขาเป็นผู้บริสุทธิ์", level: "hard" },
    { en: "I assume that you have already finished eating", th: "ฉันสันนิษฐานว่าคุณทานอาหารเสร็จเรียบร้อยแล้ว", level: "hard" },
    // --- ระดับยากพิเศษ (Extra Hard & Long Sentences) ---
    { en: "Although it was raining heavily, we decided to go out for a walk in the park", th: "ถึงแม้อากาศจะฝนตกหนัก พวกเราก็ตัดสินใจออกไปเดินเล่นในสวนสาธารณะ", level: "hard" },
    { en: "If I had known that you were coming, I would have prepared a delicious dinner for you", th: "ถ้าฉันรู้ว่าคุณจะมา ฉันคงเตรียมอาหารเย็นแสนอร่อยไว้ให้คุณแล้ว", level: "hard" },
    { en: "She was so exhausted from working all day that she fell asleep on the sofa immediately", th: "เธอเหนื่อยล้าจากการทำงานทั้งวันมากจนผล็อยหลับไปบนโซฟาทันที", level: "hard" },
    { en: "The teacher explained the difficult lesson so clearly that everyone understood it perfectly", th: "ครูอธิบายบทเรียนที่ยากนั้นอย่างชัดเจนจนทุกคนเข้าใจมันอย่างสมบูรณ์", level: "hard" },
    { en: "I have been living in this beautiful city since I graduated from university ten years ago", th: "ฉันอาศัยอยู่ในเมืองที่สวยงามแห่งนี้มาตั้งแต่ฉันเรียนจบมหาวิทยาลัยเมื่อสิบปีก่อน", level: "hard" },
    { en: "It is important to brush your teeth at least twice a day to keep them healthy", th: "มันสำคัญที่จะแปรงฟันอย่างน้อยวันละสองครั้งเพื่อรักษาให้ฟันแข็งแรง", level: "hard" },
    { en: "He promised to call me as soon as he arrived at the airport, but he forgot", th: "เขาสัญญาว่าจะโทรหาฉันทันทีที่เขาไปถึงสนามบิน แต่เขาก็ลืม", level: "hard" },
    { en: "While I was waiting for the bus, I saw an old friend whom I hadn't seen for years", th: "ขณะที่ฉันกำลังรอรถบัส ฉันเห็นเพื่อนเก่าคนหนึ่งที่ฉันไม่ได้เจอมาหลายปี", level: "hard" },
    { en: "Unless you study harder and pay attention in class, you will not pass the final exam", th: "เว้นแต่คุณจะเรียนให้หนักขึ้นและตั้งใจเรียนในห้อง คุณจะสอบปลายภาคไม่ผ่าน", level: "hard" },
    { en: "The book which you gave me for my birthday is the most interesting book I have ever read", th: "หนังสือที่คุณให้ฉันในวันเกิดคือหนังสือที่น่าสนใจที่สุดเท่าที่ฉันเคยอ่านมา", level: "hard" },
    { en: "I would rather stay at home and watch a movie than go out to a crowded party tonight", th: "ฉันอยากอยู่บ้านและดูหนังมากกว่าที่จะออกไปงานปาร์ตี้ที่คนพลุกพล่านในคืนนี้", level: "hard" },
    { en: "She asked me if I could help her carry these heavy bags to her car in the parking lot", th: "เธอถามฉันว่าฉันพอจะช่วยเธอถือกระเป๋าหนักๆ พวกนี้ไปที่รถของเธอในลานจอดรถได้ไหม", level: "hard" },
    { en: "Despite having a lot of money, he is not happy because he has no one to share it with", th: "แม้ว่าจะมีเงินมากมาย แต่เขาก็ไม่มีความสุขเพราะเขาไม่มีใครที่จะแบ่งปันด้วย", level: "hard" },
    { en: "We were supposed to meet at the cinema at six o'clock, but I was stuck in traffic", th: "พวกเราควรจะเจอกันที่โรงหนังตอนหกโมง แต่ฉันติดอยู่ในการจราจร", level: "hard" },
    { en: "Not only is she beautiful and intelligent, but she is also very kind and helpful to others", th: "ไม่เพียงแต่เธอจะสวยและฉลาด แต่เธอยังใจดีและชอบช่วยเหลือผู้อื่นอีกด้วย", level: "hard" },
    { en: "I regret not listening to my parents' advice when I was young and foolish", th: "ฉันเสียใจที่ไม่ได้ฟังคำแนะนำของพ่อแม่ตอนที่ฉันยังเด็กและโง่เขลา", level: "hard" },
    { en: "The scientist discovered a new species of butterfly in the rainforest of South America", th: "นักวิทยาศาสตร์ค้นพบผีเสื้อสายพันธุ์ใหม่ในป่าฝนของอเมริกาใต้", level: "hard" },
    { en: "It is strictly forbidden to take photographs inside the museum without special permission", th: "ห้ามถ่ายภาพภายในพิพิธภัณฑ์โดยเด็ดขาดหากไม่ได้รับอนุญาตเป็นพิเศษ", level: "hard" },
    { en: "He apologized for being late and explained that his car had broken down on the highway", th: "เขาขอโทษที่มาสายและอธิบายว่ารถของเขาเสียบนทางด่วน", level: "hard" },
    { en: "I am looking forward to visiting my grandparents in the countryside next summer holiday", th: "ฉันกำลังตั้งตารอที่จะไปเยี่ยมปู่ย่าตายายในชนบทในช่วงวันหยุดฤดูร้อนหน้า", level: "hard" },
    { en: "If I were you, I would take that job offer because it is a great opportunity for your career", th: "ถ้าฉันเป็นคุณ ฉันจะรับข้อเสนองานนั้นเพราะมันเป็นโอกาสที่ดีมากสำหรับอาชีพของคุณ", level: "hard" },
    { en: "She spent the whole afternoon cleaning her room and arranging her books on the shelves", th: "เธอใช้เวลาตลอดบ่ายทำความสะอาดห้องของเธอและจัดหนังสือบนชั้นวาง", level: "hard" },
    { en: "The man who is wearing a black suit and holding a briefcase is the manager of this company", th: "ผู้ชายคนที่สวมสูทสีดำและถือกระเป๋าเอกสารคือผู้จัดการของบริษัทนี้", level: "hard" },
    { en: "Before you make a decision, you should consider all the possible consequences carefully", th: "ก่อนที่คุณจะตัดสินใจ คุณควรพิจารณาผลที่ตามมาที่เป็นไปได้ทั้งหมดอย่างระมัดระวัง", level: "hard" },
    { en: "I have never been to a place as peaceful and beautiful as this island before in my life", th: "ฉันไม่เคยไปสถานที่ที่เงียบสงบและสวยงามเหมือนเกาะนี้มาก่อนในชีวิตของฉัน", level: "hard" },
    { en: "Because of the heavy snow, all schools in the city were closed for three days last week", th: "เนื่องจากหิมะตกหนัก โรงเรียนทุกแห่งในเมืองจึงถูกปิดเป็นเวลาสามวันเมื่อสัปดาห์ที่แล้ว", level: "hard" },
    { en: "He managed to finish the marathon in less than three hours despite his leg injury", th: "เขาจัดการวิ่งมาราธอนจนจบในเวลาน้อยกว่าสามชั่วโมงแม้ว่าจะมีการบาดเจ็บที่ขา", level: "hard" },
    { en: "Do you think that technology has made our lives easier or more complicated in the modern world", th: "คุณคิดว่าเทคโนโลยีทำให้ชีวิตของเราง่ายขึ้นหรือซับซ้อนขึ้นในโลกสมัยใหม่", level: "hard" },
    { en: "I was wondering if you would like to join us for a cup of coffee after work today", th: "ฉันสงสัยว่าคุณอยากจะไปดื่มกาแฟกับพวกเราหลังเลิกงานวันนี้ไหม", level: "hard" },
    { en: "The old house at the end of the street has been abandoned for more than twenty years", th: "บ้านหลังเก่าที่สุดถนนถูกทิ้งร้างมานานกว่ายี่สิบปีแล้ว", level: "hard" },
    { en: "She is capable of speaking four languages fluently because she loves learning new cultures", th: "เธอมีความสามารถในการพูดสี่ภาษาได้อย่างคล่องแคล่วเพราะเธอรักการเรียนรู้วัฒนธรรมใหม่ๆ", level: "hard" },
    { en: "Whatever you decide to do, make sure that it makes you happy and does not hurt anyone", th: "ไม่ว่าคุณจะตัดสินใจทำอะไร จงแน่ใจว่ามันทำให้คุณมีความสุขและไม่ทำร้ายใคร", level: "hard" },
    { en: "I remember playing in this park with my friends when we were just little children", th: "ฉันจำได้ว่าเคยเล่นในสวนสาธารณะแห่งนี้กับเพื่อนๆ ตอนที่พวกเรายังเป็นเด็กตัวเล็กๆ", level: "hard" },
    { en: "The police officer told the driver to stop the car and show his driving license immediately", th: "เจ้าหน้าที่ตำรวจบอกให้คนขับหยุดรถและแสดงใบขับขี่ทันที", level: "hard" },
    { en: "It is necessary for students to complete their homework before watching television or playing games", th: "มันจำเป็นสำหรับนักเรียนที่จะทำการบ้านให้เสร็จก่อนดูทีวีหรือเล่นเกม", level: "hard" },
    { en: "She was surprised to find out that her best friend was moving to another country next month", th: "เธอประหลาดใจที่ได้รู้ว่าเพื่อนสนิทของเธอกำลังจะย้ายไปประเทศอื่นในเดือนหน้า", level: "hard" },
    { en: "There are many reasons why people choose to live in the city rather than in the countryside", th: "มีเหตุผลมากมายว่าทำไมผู้คนถึงเลือกที่จะอาศัยอยู่ในเมืองมากกว่าในชนบท", level: "hard" },
    { en: "He refused to accept the gift because he felt that it was too expensive for him to take", th: "เขาปฏิเสธที่จะรับของขวัญเพราะเขารู้สึกว่ามันแพงเกินไปสำหรับเขาที่จะรับไว้", level: "hard" },
    { en: "I strongly believe that education is the most powerful weapon which you can use to change the world", th: "ฉันเชื่ออย่างแรงกล้าว่าการศึกษาคืออาวุธที่ทรงพลังที่สุดที่คุณสามารถใช้เพื่อเปลี่ยนแปลงโลก", level: "hard" },
    { en: "Even though she was very tired, she continued working until the project was completely finished", th: "ถึงแม้ว่าเธอจะเหนื่อยมาก เธอก็ยังคงทำงานต่อไปจนกระทั่งโปรเจกต์เสร็จสมบูรณ์", level: "hard" },
    { en: "The restaurant where we had dinner last night served the most delicious Italian food I have ever tasted", th: "ร้านอาหารที่พวกเราไปกินมื้อเย็นเมื่อคืนเสิร์ฟอาหารอิตาเลียนที่อร่อยที่สุดเท่าที่ฉันเคยชิม", level: "hard" },
    { en: "I wish I could travel back in time to see what life was like in the ancient world", th: "ฉันหวังว่าฉันจะสามารถย้อนเวลากลับไปดูว่าชีวิตเป็นอย่างไรในโลกยุคโบราณ", level: "hard" },
    { en: "He is the only person in this room who knows how to operate this complicated machine properly", th: "เขาเป็นคนเดียวในห้องนี้ที่รู้วิธีใช้งานเครื่องจักรที่ซับซ้อนนี้อย่างถูกต้อง", level: "hard" },
    { en: "By the time we arrived at the station, the train had already left and we had to wait for the next one", th: "กว่าพวกเราจะไปถึงสถานี รถไฟก็ออกไปแล้วและพวกเราต้องรอขบวนถัดไป", level: "hard" },
    { en: "She suggested that we should organize a surprise party for our teacher's retirement next week", th: "เธอเสนอว่าพวกเราควรจัดงานปาร์ตี้เซอร์ไพรส์สำหรับการเกษียณของครูในสัปดาห์หน้า", level: "hard" },
    { en: "It seems that the economy is improving slowly after the crisis that happened two years ago", th: "ดูเหมือนว่าเศรษฐกิจกำลังดีขึ้นอย่างช้าๆ หลังจากวิกฤตที่เกิดขึ้นเมื่อสองปีก่อน", level: "hard" },
    { en: "I have no doubt that he will become a successful businessman in the future because he works very hard", th: "ฉันไม่มีข้อสงสัยเลยว่าเขาจะกลายเป็นนักธุรกิจที่ประสบความสำเร็จในอนาคตเพราะเขาทำงานหนักมาก", level: "hard" },
    { en: "The instructions on the box were so confusing that I could not figure out how to assemble the toy", th: "คำแนะนำบนกล่องนั้นน่าสับสนมากจนฉันคิดไม่ออกว่าจะประกอบของเล่นยังไง", level: "hard" },
    { en: "She always carries a notebook with her so that she can write down any interesting ideas she has", th: "เธอพกสมุดโน้ตติดตัวเสมอเพื่อที่เธอจะได้จดไอเดียที่น่าสนใจที่เธอมี", level: "hard" },
    { en: "We should take care of our planet by recycling waste and using renewable energy sources", th: "เราควรดูแลโลกของเราโดยการรีไซเคิลขยะและใช้แหล่งพลังงานหมุนเวียน", level: "hard" },   
   // --- เพิ่มเติมชุดที่ 2: ระดับยากพิเศษ (More Extra Hard & Long Sentences) ---
    { en: "No matter how hard he tried, he could not remember where he had hidden the treasure map", th: "ไม่ว่าเขาจะพยายามอย่างหนักแค่ไหน เขาก็จำไม่ได้ว่าเขาซ่อนแผนที่สมบัติไว้ที่ไหน", level: "hard" },
    { en: "The documentary that we watched in class yesterday changed my perspective on global warming", th: "สารคดีที่พวกเราดูในห้องเรียนเมื่อวานนี้เปลี่ยนมุมมองของฉันเกี่ยวกับภาวะโลกร้อน", level: "hard" },
    { en: "If you had told me earlier that you were vegetarians, I would have cooked something else", th: "ถ้าคุณบอกฉันก่อนหน้านี้ว่าเป็นมังสวิรัติ ฉันคงทำอาหารอย่างอื่นให้แล้ว", level: "hard" },
    { en: "She was disappointed to learn that the concert had been cancelled due to technical problems", th: "เธอผิดหวังที่ได้รู้ว่าคอนเสิร์ตถูกยกเลิกเนื่องจากปัญหาทางเทคนิค", level: "hard" },
    { en: "It is widely believed that learning a musical instrument helps improve memory and concentration", th: "เป็นที่เชื่อกันอย่างกว้างขวางว่าการเรียนดนตรีช่วยปรับปรุงความจำและสมาธิ", level: "hard" },
    { en: "He explained that he could not attend the meeting because he had a dentist appointment", th: "เขาอธิบายว่าเขาไม่สามารถเข้าร่วมการประชุมได้เพราะเขามีนัดทำฟัน", level: "hard" },
    { en: "The massive storm destroyed many houses and caused a power outage in the entire city", th: "พายุลูกใหญ่ทำลายบ้านเรือนหลายหลังและทำให้ไฟดับทั่วทั้งเมือง", level: "hard" },
    { en: "I would be grateful if you could send me the details of the project by email tonight", th: "ฉันจะขอบคุณมากถ้าคุณสามารถส่งรายละเอียดโครงการให้ฉันทางอีเมลคืนนี้", level: "hard" },
    { en: "Despite the fact that he is very rich, he lives a simple life in a small wooden house", th: "แม้ว่าความจริงแล้วเขาจะรวยมาก แต่เขาก็ใช้ชีวิตเรียบง่ายในบ้านไม้หลังเล็กๆ", level: "hard" },
    { en: "The children were so excited about the field trip that they could not sleep last night", th: "เด็กๆ ตื่นเต้นกับการไปทัศนศึกษามากจนพวกเขานอนไม่หลับเมื่อคืนนี้", level: "hard" },
    { en: "You should not make promises that you cannot keep because it will hurt people's feelings", th: "คุณไม่ควรให้สัญญาที่คุณรักษาไม่ได้เพราะมันจะทำร้ายความรู้สึกของผู้คน", level: "hard" },
    { en: "She has been studying architecture for five years and dreams of designing her own house", th: "เธอเรียนสถาปัตยกรรมมาห้าปีแล้วและฝันที่จะออกแบบบ้านของเธอเอง", level: "hard" },
    { en: "The traffic jam was so bad that we missed the beginning of the movie at the cinema", th: "รถติดแย่มากจนพวกเราพลาดช่วงเริ่มต้นของหนังที่โรงภาพยนตร์", level: "hard" },
    { en: "I wonder if it is possible to learn two languages at the same time without getting confused", th: "ฉันสงสัยว่าเป็นไปได้ไหมที่จะเรียนสองภาษาไปพร้อมกันโดยไม่สับสน", level: "hard" },
    { en: "He was awarded a gold medal for his outstanding contribution to the field of science", th: "เขาได้รับเหรียญทองสำหรับการอุทิศตนที่โดดเด่นให้กับวงการวิทยาศาสตร์", level: "hard" },
    { en: "Unless we take action now to save the environment, future generations will suffer greatly", th: "เว้นแต่เราจะลงมือทำตอนนี้เพื่อรักษาสิ่งแวดล้อม คนรุ่นหลังจะเดือดร้อนอย่างหนัก", level: "hard" },
    { en: "The mysterious woman sitting in the corner of the cafe looked as if she was waiting for a spy", th: "ผู้หญิงลึกลับที่นั่งอยู่ตรงมุมคาเฟ่ดูราวกับว่าเธอกำลังรอสายลับอยู่", level: "hard" },
    { en: "I realized that I had left my wallet at home when I was standing at the checkout counter", th: "ฉันตระหนักได้ว่าฉันลืมกระเป๋าสตางค์ไว้ที่บ้านตอนที่ฉันยืนอยู่ที่เคาน์เตอร์ชำระเงิน", level: "hard" },
    { en: "She encouraged her son to pursue his dream of becoming a professional football player", th: "เธอสนับสนุนลูกชายของเธอให้ไล่ตามความฝันที่จะเป็นนักฟุตบอลอาชีพ", level: "hard" },
    { en: "The ancient castle on top of the hill offers a breathtaking view of the surrounding valley", th: "ปราสาทโบราณบนยอดเขามีวิวที่น่าทึ่งของหุบเขาโดยรอบ", level: "hard" },
    { en: "It is high time that we started thinking about how to reduce the amount of plastic waste", th: "มันถึงเวลาแล้วที่เราจะเริ่มคิดเกี่ยวกับวิธีลดปริมาณขยะพลาสติก", level: "hard" },
    { en: "He refused to admit his mistake even though everyone knew that it was his fault", th: "เขาปฏิเสธที่จะยอมรับความผิดพลาดแม้ว่าทุกคนจะรู้ว่ามันเป็นความผิดของเขา", level: "hard" },
    { en: "If I were in your shoes, I would apologize to her immediately to avoid further arguments", th: "ถ้าฉันตกอยู่ในสถานการณ์ของคุณ ฉันจะขอโทษเธอทันทีเพื่อหลีกเลี่ยงการโต้เถียงเพิ่มเติม", level: "hard" },
    { en: "The book explains complex scientific theories in a way that is easy for anyone to understand", th: "หนังสือเล่มนี้อธิบายทฤษฎีวิทยาศาสตร์ที่ซับซ้อนในแบบที่ง่ายสำหรับทุกคนที่จะเข้าใจ", level: "hard" },
    { en: "We were lucky to find a parking space right in front of the entrance to the shopping mall", th: "พวกเราโชคดีที่เจอที่จอดรถตรงหน้าทางเข้าห้างสรรพสินค้าพอดี", level: "hard" },
    { en: "She decided to start her own business instead of working for a large corporation", th: "เธอตัดสินใจเริ่มต้นธุรกิจของตัวเองแทนที่จะทำงานให้กับบริษัทใหญ่", level: "hard" },
    { en: "The longer you wait to see a doctor, the worse your condition might become in the future", th: "ยิ่งคุณรอไปหาหมอนานเท่าไหร่ อาการของคุณอาจจะแย่ลงในอนาคต", level: "hard" },
    { en: "I have always wanted to learn how to fly a plane since I was a little boy", th: "ฉันอยากเรียนรู้วิธีขับเครื่องบินมาตลอดตั้งแต่ฉันยังเป็นเด็กชายตัวเล็กๆ", level: "hard" },
    { en: "The unexpected news about the merger of the two companies surprised all the employees", th: "ข่าวที่ไม่คาดคิดเกี่ยวกับการควบรวมกิจการของสองบริษัททำให้พนักงานทุกคนประหลาดใจ", level: "hard" },
    { en: "It is unfair to judge people by their appearance without knowing their true personality", th: "มันไม่ยุติธรรมที่จะตัดสินผู้คนจากรูปลักษณ์ภายนอกโดยไม่รู้นิสัยที่แท้จริงของพวกเขา", level: "hard" },
    { en: "He spent a fortune on renovating the old farmhouse that he inherited from his grandfather", th: "เขาใช้เงินมหาศาลในการบูรณะบ้านไร่หลังเก่าที่เขาได้รับมรดกมาจากปู่", level: "hard" },
    { en: "I am confident that you have the ability to overcome any obstacles in your life", th: "ฉันมั่นใจว่าคุณมีความสามารถที่จะเอาชนะอุปสรรคใดๆ ในชีวิตของคุณได้", level: "hard" },
    { en: "The silence in the library was broken by the sound of a heavy book falling on the floor", th: "ความเงียบในห้องสมุดถูกทำลายโดยเสียงของหนังสือเล่มหนาตกลงบนพื้น", level: "hard" },
    { en: "She claimed that she had seen a UFO while she was camping in the mountains alone", th: "เธออ้างว่าเธอเห็นจานบินขณะที่เธอกำลังตั้งแคมป์ในภูเขาคนเดียว", level: "hard" },
    { en: "We should appreciate the little things in life because they often matter the most", th: "เราควรเห็นคุณค่าของสิ่งเล็กๆ ในชีวิตเพราะสิ่งเหล่านั้นมักจะสำคัญที่สุด", level: "hard" },
    { en: "He hesitated for a moment before answering the difficult question asked by the interviewer", th: "เขาลังเลอยู่ครู่หนึ่งก่อนที่จะตอบคำถามยากๆ ที่ผู้สัมภาษณ์ถาม", level: "hard" },
    { en: "I would like to congratulate you on your graduation and wish you success in your career", th: "ฉันขอแสดงความยินดีกับคุณที่เรียนจบและขอให้คุณประสบความสำเร็จในอาชีพ", level: "hard" },
    { en: "The painting which was stolen from the museum last week has finally been recovered by police", th: "ภาพวาดที่ถูกขโมยไปจากพิพิธภัณฑ์เมื่อสัปดาห์ที่แล้วในที่สุดก็ถูกตำรวจกู้คืนมาได้", level: "hard" },
    { en: "It is generally agreed that exercising regularly leads to a healthier and happier life", th: "เป็นที่ตกลงกันโดยทั่วไปว่าการออกกำลังกายสม่ำเสมอนำไปสู่ชีวิตที่มีสุขภาพดีและมีความสุขกว่า", level: "hard" },
    { en: "She wrapped the gift carefully in colorful paper and tied it with a beautiful red ribbon", th: "เธอห่อของขวัญอย่างระมัดระวังด้วยกระดาษหลากสีและผูกด้วยริบบิ้นสีแดงที่สวยงาม", level: "hard" },
    { en: "The reason why I am calling you so late is that I have some urgent news to tell you", th: "เหตุผลที่ฉันโทรหาคุณดึกขนาดนี้คือฉันมีข่าวด่วนจะบอกคุณ", level: "hard" },
    { en: "Having finished his homework, he was finally allowed to go out and play with his friends", th: "หลังจากทำการบ้านเสร็จ ในที่สุดเขาก็ได้รับอนุญาตให้ออกไปเล่นกับเพื่อนๆ", level: "hard" },
    { en: "I suspect that someone has been reading my diary because it was not in its usual place", th: "ฉันสงสัยว่ามีคนแอบอ่านไดอารี่ของฉันเพราะมันไม่อยู่ในที่ปกติของมัน", level: "hard" },
    { en: "The heavy rain continued for three days causing floods in many parts of the country", th: "ฝนที่ตกหนักต่อเนื่องเป็นเวลาสามวันทำให้เกิดน้ำท่วมในหลายพื้นที่ของประเทศ", level: "hard" },
    { en: "You had better leave now if you want to catch the last bus back to the city center", th: "คุณควรรีบไปตอนนี้ดีกว่าถ้าคุณอยากจะขึ้นรถบัสเที่ยวสุดท้ายกลับเข้าเมือง", level: "hard" },
    { en: "She wondered what her life would be like if she had chosen a different career path", th: "เธอสงสัยว่าชีวิตของเธอจะเป็นอย่างไรถ้าเธอเลือกเส้นทางอาชีพที่แตกต่างออกไป", level: "hard" },
    { en: "The scientist dedicated his entire life to finding a cure for this rare and deadly disease", th: "นักวิทยาศาสตร์อุทิศทั้งชีวิตของเขาเพื่อค้นหาวิธีรักษาโรคหายากและร้ายแรงนี้", level: "hard" },
    { en: "Whatever challenges you face, remember that you have friends who will always support you", th: "ไม่ว่าคุณจะเผชิญกับความท้าทายอะไร จำไว้ว่าคุณมีเพื่อนที่จะคอยสนับสนุนคุณเสมอ", level: "hard" },
    { en: "I was about to leave the house when I remembered that I had left the oven on", th: "ฉันกำลังจะออกจากบ้านพอดีตอนที่ฉันนึกขึ้นได้ว่าฉันเปิดเตาอบทิ้งไว้", level: "hard" },
    { en: "The beauty of nature is something that we often take for granted in our busy lives", th: "ความงามของธรรมชาติคือสิ่งที่เรามักมองข้ามไปในชีวิตที่ยุ่งวุ่นวายของเรา", level: "hard" } 
];
