// ไฟล์: verbs3.js
// รวมคำศัพท์กริยา 3 ช่อง (A-Z)
const irregularVerbs = [
    // --- A ---
    { word: "arise - arose - arisen", read: "อะไรส์ - อะโรส - อะริสเซ่น", meaning: "เกิดขึ้น", category: "verbs3" },
    { word: "awake - awoke - awoken", read: "อะเวค - อะโวค - อะโวคเค่น", meaning: "ตื่น", category: "verbs3" },
    // --- B ---
    { word: "be - was/were - been", read: "บี - วอส/เวอ - บีน", meaning: "เป็น / อยู่ / คือ", category: "verbs3" },
    { word: "bear - bore - born", read: "แบร์ - บอร์ - บอร์น", meaning: "ทน / ให้กำเนิด", category: "verbs3" },
    { word: "beat - beat - beaten", read: "บีท - บีท - บีทเท่น", meaning: "ตี / ชนะ", category: "verbs3" },
    { word: "become - became - become", read: "บีคัม - บีเคม - บีคัม", meaning: "กลายเป็น", category: "verbs3" },
    { word: "begin - began - begun", read: "บีกิน - บีแกน - บีกัน", meaning: "เริ่มต้น", category: "verbs3" },
    { word: "bend - bent - bent", read: "เบนด์ - เบนท์ - เบนท์", meaning: "โค้ง / งอ", category: "verbs3" },
    { word: "bet - bet - bet", read: "เบท - เบท - เบท", meaning: "พนัน", category: "verbs3" },
    { word: "bind - bound - bound", read: "ไบน์ - บาวด์ - บาวด์", meaning: "ผูก / มัด", category: "verbs3" },
    { word: "bite - bit - bitten", read: "ไบท์ - บิท - บิทเท่น", meaning: "กัด", category: "verbs3" },
    { word: "bleed - bled - bled", read: "บลีด - เบลด - เบลด", meaning: "เลือดออก", category: "verbs3" },
    { word: "blow - blew - blown", read: "โบลว์ - บลู - โบลน", meaning: "เป่า / พัด", category: "verbs3" },
    { word: "break - broke - broken", read: "เบรค - โบรค - โบรคเค็น", meaning: "แตก / หัก", category: "verbs3" },
    { word: "breed - bred - bred", read: "บรีด - เบรด - เบรด", meaning: "ผสมพันธุ์", category: "verbs3" },
    { word: "bring - brought - brought", read: "บริง - บรอท - บรอท", meaning: "นำมา", category: "verbs3" },
    { word: "broadcast - broadcast - broadcast", read: "บรอดแคสต์ (3 ช่องเหมือนกัน)", meaning: "ออกอากาศ", category: "verbs3" },
    { word: "build - built - built", read: "บิลด์ - บิลท์ - บิลท์", meaning: "สร้าง", category: "verbs3" },
    { word: "burn - burnt - burnt", read: "เบิร์น - เบิร์นท์ - เบิร์นท์", meaning: "เผา / ไหม้", category: "verbs3" },
    { word: "burst - burst - burst", read: "เบิร์สท์ - เบิร์สท์ - เบิร์สท์", meaning: "ระเบิดออก", category: "verbs3" },
    { word: "buy - bought - bought", read: "บาย - บอท - บอท", meaning: "ซื้อ", category: "verbs3" },
    // --- C ---
    { word: "catch - caught - caught", read: "แคทช์ - คอท - คอท", meaning: "จับ", category: "verbs3" },
    { word: "choose - chose - chosen", read: "ชูส - โชส - โชสเซ่น", meaning: "เลือก", category: "verbs3" },
    { word: "cling - clung - clung", read: "คลิง - คลัง - คลัง", meaning: "เกาะแน่น", category: "verbs3" },
    { word: "come - came - come", read: "คัม - เคม - คัม", meaning: "มา", category: "verbs3" },
    { word: "cost - cost - cost", read: "คอสต์ - คอสต์ - คอสต์", meaning: "มีราคา", category: "verbs3" },
    { word: "creep - crept - crept", read: "ครีพ - เครพท์ - เครพท์", meaning: "คลาน", category: "verbs3" },
    { word: "cut - cut - cut", read: "คัท - คัท - คัท", meaning: "ตัด", category: "verbs3" },
    // --- D ---
    { word: "deal - dealt - dealt", read: "ดีล - เดลท์ - เดลท์", meaning: "จัดการ / แจกไพ่", category: "verbs3" },
    { word: "dig - dug - dug", read: "ดิ๊ก - ดั๊ก - ดั๊ก", meaning: "ขุด", category: "verbs3" },
    { word: "do - did - done", read: "ดู - ดิ๊ด - ดัน", meaning: "ทำ", category: "verbs3" },
    { word: "draw - drew - drawn", read: "ดรอ - ดรู - ดรอน", meaning: "วาด / ดึง", category: "verbs3" },
    { word: "dream - dreamt - dreamt", read: "ดรีม - เดรมท์ - เดรมท์", meaning: "ฝัน", category: "verbs3" },
    { word: "drink - drank - drunk", read: "ดริงค์ - แดรงค์ - ดรังค์", meaning: "ดื่ม", category: "verbs3" },
    { word: "drive - drove - driven", read: "ไดรฟ์ - โดรฟ - ไดรฟ์เว่น", meaning: "ขับรถ", category: "verbs3" },
    // --- E ---
    { word: "eat - ate - eaten", read: "อีท - เอท - อีทเท่น", meaning: "กิน", category: "verbs3" },
    // --- F ---
    { word: "fall - fell - fallen", read: "ฟอล - เฟล - ฟอลเล่น", meaning: "ตก / หล่น", category: "verbs3" },
    { word: "feed - fed - fed", read: "ฟีด - เฟด - เฟด", meaning: "ให้อาหาร", category: "verbs3" },
    { word: "feel - felt - felt", read: "ฟีล - เฟลท์ - เฟลท์", meaning: "รู้สึก", category: "verbs3" },
    { word: "fight - fought - fought", read: "ไฟท์ - ฟอท - ฟอท", meaning: "ต่อสู้", category: "verbs3" },
    { word: "find - found - found", read: "ไฟนด์ - ฟาวด์ - ฟาวด์", meaning: "พบ / เจอ", category: "verbs3" },
    { word: "flee - fled - fled", read: "ฟลี - เฟลด - เฟลด", meaning: "หลบหนี", category: "verbs3" },
    { word: "fly - flew - flown", read: "ฟลาย - ฟลู - โฟลน", meaning: "บิน", category: "verbs3" },
    { word: "forbid - forbade - forbidden", read: "ฟอร์บิด - ฟอร์เบด - ฟอร์บิดเด่น", meaning: "ห้าม", category: "verbs3" },
    { word: "forget - forgot - forgotten", read: "ฟอร์เก็ท - ฟอร์กอท - ฟอร์กอทเท่น", meaning: "ลืม", category: "verbs3" },
    { word: "forgive - forgave - forgiven", read: "ฟอร์กีฟ - ฟอร์เกฟ - ฟอร์กีฟเว่น", meaning: "ให้อภัย", category: "verbs3" },
    { word: "freeze - froze - frozen", read: "ฟรีซ - โฟรซ - โฟรซเซ่น", meaning: "แช่แข็ง", category: "verbs3" },
    // --- G ---
    { word: "get - got - gotten", read: "เก็ท - กอท - กอทเท่น", meaning: "ได้รับ", category: "verbs3" },
    { word: "give - gave - given", read: "กีฟ - เกฟ - กีฟเว่น", meaning: "ให้", category: "verbs3" },
    { word: "go - went - gone", read: "โก - เว็นท - กอน", meaning: "ไป", category: "verbs3" },
    { word: "grind - ground - ground", read: "ไกรนด์ - กราวด์ - กราวด์", meaning: "บด", category: "verbs3" },
    { word: "grow - grew - grown", read: "โกร - กรู - โกรน", meaning: "เติบโต / ปลูก", category: "verbs3" },
    // --- H ---
    { word: "hang - hung - hung", read: "แฮง - ฮัง - ฮัง", meaning: "แขวน", category: "verbs3" },
    { word: "have - had - had", read: "แฮฟ - แฮด - แฮด", meaning: "มี", category: "verbs3" },
    { word: "hear - heard - heard", read: "เฮียร์ - เฮิร์ด - เฮิร์ด", meaning: "ได้ยิน", category: "verbs3" },
    { word: "hide - hid - hidden", read: "ไฮด์ - ฮิด - ฮิดเด่น", meaning: "ซ่อน", category: "verbs3" },
    { word: "hit - hit - hit", read: "ฮิท - ฮิท - ฮิท", meaning: "ตี / ชน", category: "verbs3" },
    { word: "hold - held - held", read: "โฮลด์ - เฮลด - เฮลด", meaning: "ถือ / จัดงาน", category: "verbs3" },
    { word: "hurt - hurt - hurt", read: "เฮิร์ท - เฮิร์ท - เฮิร์ท", meaning: "ทำให้เจ็บ", category: "verbs3" },
    // --- K ---
    { word: "keep - kept - kept", read: "คีพ - เคพท์ - เคพท์", meaning: "เก็บรักษา", category: "verbs3" },
    { word: "kneel - knelt - knelt", read: "นีล - เนลท์ - เนลท์", meaning: "คุกเข่า", category: "verbs3" },
    { word: "know - knew - known", read: "โน - นู - โนน", meaning: "รู้ / รู้จัก", category: "verbs3" },
    // --- L ---
    { word: "lay - laid - laid", read: "เลย์ - เลด - เลด", meaning: "วางลง", category: "verbs3" },
    { word: "lead - led - led", read: "ลีด - เลด - เลด", meaning: "นำ", category: "verbs3" },
    { word: "lean - leant - leant", read: "ลีน - เลนท์ - เลนท์", meaning: "พิง", category: "verbs3" },
    { word: "learn - learnt - learnt", read: "เลิร์น - เลิร์นท์ - เลิร์นท์", meaning: "เรียนรู้", category: "verbs3" },
    { word: "leave - left - left", read: "ลีฟ - เลฟท์ - เลฟท์", meaning: "ออกจาก / ทิ้งไว้", category: "verbs3" },
    { word: "lend - lent - lent", read: "เลนด์ - เลนท์ - เลนท์", meaning: "ให้ยืม", category: "verbs3" },
    { word: "let - let - let", read: "เล็ท - เล็ท - เล็ท", meaning: "อนุญาต / ปล่อย", category: "verbs3" },
    { word: "lie - lay - lain", read: "ไล - เลย์ - เลน", meaning: "นอนลง", category: "verbs3" },
    { word: "light - lit - lit", read: "ไลท์ - ลิท - ลิท", meaning: "จุดไฟ", category: "verbs3" },
    { word: "lose - lost - lost", read: "ลูส - ลอสต์ - ลอสต์", meaning: "ทำหาย / แพ้", category: "verbs3" },
    // --- M ---
    { word: "make - made - made", read: "เมค - เมด - เมด", meaning: "ทำ / สร้าง", category: "verbs3" },
    { word: "mean - meant - meant", read: "มีน - เมนท์ - เมนท์", meaning: "หมายความว่า", category: "verbs3" },
    { word: "meet - met - met", read: "มีท - เมท - เมท", meaning: "พบ", category: "verbs3" },
    // --- P ---
    { word: "pay - paid - paid", read: "เพย์ - เพด - เพด", meaning: "จ่าย", category: "verbs3" },
    { word: "put - put - put", read: "พุท - พุท - พุท", meaning: "วาง / ใส่", category: "verbs3" },
    // --- Q ---
    { word: "quit - quit - quit", read: "ควิต - ควิต - ควิต", meaning: "เลิก / ลาออก", category: "verbs3" },
    // --- R ---
    { word: "read - read - read", read: "รีด - เรด - เรด (เขียนเหมือนกัน)", meaning: "อ่าน", category: "verbs3" },
    { word: "ride - rode - ridden", read: "ไรด์ - โรด - ริดเด่น", meaning: "ขี่", category: "verbs3" },
    { word: "ring - rang - rung", read: "ริง - แรง - รัง", meaning: "สั่นกระดิ่ง / โทร", category: "verbs3" },
    { word: "rise - rose - risen", read: "ไรส์ - โรส - ริสเซ่น", meaning: "ขึ้น / ลุกขึ้น", category: "verbs3" },
    { word: "run - ran - run", read: "รัน - แรน - รัน", meaning: "วิ่ง", category: "verbs3" },
    // --- S ---
    { word: "say - said - said", read: "เซ - เซด - เซด", meaning: "พูด", category: "verbs3" },
    { word: "see - saw - seen", read: "ซี - ซอ - ซีน", meaning: "เห็น", category: "verbs3" },
    { word: "seek - sought - sought", read: "ซีค - ซอท - ซอท", meaning: "ค้นหา", category: "verbs3" },
    { word: "sell - sold - sold", read: "เซล - โซลด์ - โซลด์", meaning: "ขาย", category: "verbs3" },
    { word: "send - sent - sent", read: "เซนด์ - เซนท์ - เซนท์", meaning: "ส่ง", category: "verbs3" },
    { word: "set - set - set", read: "เซ็ท - เซ็ท - เซ็ท", meaning: "จัดวาง / ตั้งค่า", category: "verbs3" },
    { word: "sew - sewed - sewn", read: "โซ - โซด - โซน", meaning: "เย็บ", category: "verbs3" },
    { word: "shake - shook - shaken", read: "เชค - ชุค - เชคเค่น", meaning: "เขย่า / สั่น", category: "verbs3" },
    { word: "shine - shone - shone", read: "ไชน์ - โชน - โชน", meaning: "ส่องแสง", category: "verbs3" },
    { word: "shoot - shot - shot", read: "ชูท - ชอท - ชอท", meaning: "ยิง", category: "verbs3" },
    { word: "show - showed - shown", read: "โชว์ - โชว์ด - โชน", meaning: "แสดง", category: "verbs3" },
    { word: "shrink - shrank - shrunk", read: "ชริงค์ - แชรงค์ - ชรังค์", meaning: "หดตัว", category: "verbs3" },
    { word: "shut - shut - shut", read: "ชัท - ชัท - ชัท", meaning: "ปิด", category: "verbs3" },
    { word: "sing - sang - sung", read: "ซิง - แซง - ซัง", meaning: "ร้องเพลง", category: "verbs3" },
    { word: "sink - sank - sunk", read: "ซิงค์ - แซงค์ - ซังค์", meaning: "จม", category: "verbs3" },
    { word: "sit - sat - sat", read: "ซิท - แซท - แซท", meaning: "นั่ง", category: "verbs3" },
    { word: "sleep - slept - slept", read: "สลีป - สเลพท์ - สเลพท์", meaning: "นอนหลับ", category: "verbs3" },
    { word: "slide - slid - slid", read: "สไลด์ - สลิด - สลิด", meaning: "ลื่นไถล", category: "verbs3" },
    { word: "smell - smelt - smelt", read: "สเมล - สเมลท์ - สเมลท์", meaning: "ดมกลิ่น", category: "verbs3" },
    { word: "speak - spoke - spoken", read: "สปีค - สโปค - สโปคเค่น", meaning: "พูด", category: "verbs3" },
    { word: "speed - sped - sped", read: "สปีด - สเปด - สเปด", meaning: "เร่งความเร็ว", category: "verbs3" },
    { word: "spell - spelt - spelt", read: "สเปล - สเปลท์ - สเปลท์", meaning: "สะกดคำ", category: "verbs3" },
    { word: "spend - spent - spent", read: "สเปนด์ - สเปนท์ - สเปนท์", meaning: "ใช้จ่าย / ใช้เวลา", category: "verbs3" },
    { word: "spill - spilt - spilt", read: "สพิล - สพิลท์ - สพิลท์", meaning: "ทำหก", category: "verbs3" },
    { word: "spin - spun - spun", read: "สพิน - สพัน - สพัน", meaning: "หมุน / ปั่น", category: "verbs3" },
    { word: "spit - spat - spat", read: "สพิท - สแพท - สแพท", meaning: "ถ่มน้ำลาย", category: "verbs3" },
    { word: "split - split - split", read: "สพลิต - สพลิต - สพลิต", meaning: "แยก / ผ่า", category: "verbs3" },
    { word: "spread - spread - spread", read: "สเพรด - สเพรด - สเพรด", meaning: "แผ่ / กระจาย", category: "verbs3" },
    { word: "spring - sprang - sprung", read: "สพริง - สแพรง - สพรัง", meaning: "กระโดด / ดีดตัว", category: "verbs3" },
    { word: "stand - stood - stood", read: "สแตนด์ - สตุด - สตุด", meaning: "ยืน", category: "verbs3" },
    { word: "steal - stole - stolen", read: "สตีล - สโตล - สโตลเล่น", meaning: "ขโมย", category: "verbs3" },
    { word: "stick - stuck - stuck", read: "สติ๊ค - สตั๊ค - สตั๊ค", meaning: "ติด / แปะ", category: "verbs3" },
    { word: "sting - stung - stung", read: "สติง - สตัง - สตัง", meaning: "ต่อย (แมลง)", category: "verbs3" },
    { word: "stink - stank - stunk", read: "สติงค์ - สแตงค์ - สตังค์", meaning: "ส่งกลิ่นเหม็น", category: "verbs3" },
    { word: "strike - struck - struck", read: "สไตรค์ - สตรัค - สตรัค", meaning: "ตี / ประท้วง", category: "verbs3" },
    { word: "swear - swore - sworn", read: "สแวร์ - สวอร์ - สวอร์น", meaning: "สาบาน / ด่า", category: "verbs3" },
    { word: "sweep - swept - swept", read: "สวีป - สเวพท์ - สเวพท์", meaning: "กวาด", category: "verbs3" },
    { word: "swim - swam - swum", read: "สวิม - สแวม - สวม", meaning: "ว่ายน้ำ", category: "verbs3" },
    { word: "swing - swung - swung", read: "สวิง - สวัง - สวัง", meaning: "แกว่ง", category: "verbs3" },
    // --- T ---
    { word: "take - took - taken", read: "เทค - ทุค - เทคเค่น", meaning: "นำไป / เอา", category: "verbs3" },
    { word: "teach - taught - taught", read: "ทีช - ทอท - ทอท", meaning: "สอน", category: "verbs3" },
    { word: "tear - tore - torn", read: "แทร์ - ทอร์ - ทอร์น", meaning: "ฉีกขาด", category: "verbs3" },
    { word: "tell - told - told", read: "เทล - โทลด์ - โทลด์", meaning: "บอก", category: "verbs3" },
    { word: "think - thought - thought", read: "ธิงค์ - ธอท - ธอท", meaning: "คิด", category: "verbs3" },
    { word: "throw - threw - thrown", read: "โทร - ทรู - โทรน", meaning: "ขว้าง / ปา", category: "verbs3" },
    { word: "thrust - thrust - thrust", read: "ทรัสท์ - ทรัสท์ - ทรัสท์", meaning: "ผลัก / ดันแรงๆ", category: "verbs3" },
    // --- U ---
    { word: "understand - understood - understood", read: "อันเดอร์สแตนด์ (ช่อง 2-3 อันเดอร์สตุด)", meaning: "เข้าใจ", category: "verbs3" },
    // --- W ---
    { word: "wake - woke - woken", read: "เวค - โวค - โวคเค่น", meaning: "ตื่น", category: "verbs3" },
    { word: "wear - wore - worn", read: "แวร์ - วอร์ - วอร์น", meaning: "สวมใส่", category: "verbs3" },
    { word: "weave - wove - woven", read: "วีฟ - โวฟ - โวฟเว่น", meaning: "ทอ (ผ้า)", category: "verbs3" },
    { word: "weep - wept - wept", read: "วีพ - เวพท์ - เวพท์", meaning: "ร้องไห้คร่ำครวญ", category: "verbs3" },
    { word: "win - won - won", read: "วิน - วอน - วอน", meaning: "ชนะ", category: "verbs3" },
    { word: "wind - wound - wound", read: "ไวนด์ - วาวด์ - วาวด์", meaning: "ไขลาน / พัน", category: "verbs3" },
    { word: "write - wrote - written", read: "ไรท์ - โรท - ริทเท่น", meaning: "เขียน", category: "verbs3" }
];